// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "voicerec_classifySound.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic voicerec_classifySound::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic voicerec_classifySound::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<11> voicerec_classifySound::ap_ST_st1_fsm_0 = "1";
const sc_lv<11> voicerec_classifySound::ap_ST_st2_fsm_1 = "10";
const sc_lv<11> voicerec_classifySound::ap_ST_st3_fsm_2 = "100";
const sc_lv<11> voicerec_classifySound::ap_ST_st4_fsm_3 = "1000";
const sc_lv<11> voicerec_classifySound::ap_ST_st5_fsm_4 = "10000";
const sc_lv<11> voicerec_classifySound::ap_ST_st6_fsm_5 = "100000";
const sc_lv<11> voicerec_classifySound::ap_ST_st7_fsm_6 = "1000000";
const sc_lv<11> voicerec_classifySound::ap_ST_st8_fsm_7 = "10000000";
const sc_lv<11> voicerec_classifySound::ap_ST_st9_fsm_8 = "100000000";
const sc_lv<11> voicerec_classifySound::ap_ST_st10_fsm_9 = "1000000000";
const sc_lv<11> voicerec_classifySound::ap_ST_st11_fsm_10 = "10000000000";
const sc_lv<32> voicerec_classifySound::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> voicerec_classifySound::ap_const_lv1_1 = "1";
const sc_lv<32> voicerec_classifySound::ap_const_lv32_1 = "1";
const sc_lv<1> voicerec_classifySound::ap_const_lv1_0 = "0";
const sc_lv<32> voicerec_classifySound::ap_const_lv32_2 = "10";
const sc_lv<32> voicerec_classifySound::ap_const_lv32_3 = "11";
const sc_lv<32> voicerec_classifySound::ap_const_lv32_4 = "100";
const sc_lv<32> voicerec_classifySound::ap_const_lv32_7 = "111";
const sc_lv<32> voicerec_classifySound::ap_const_lv32_8 = "1000";
const sc_lv<32> voicerec_classifySound::ap_const_lv32_9 = "1001";
const sc_lv<32> voicerec_classifySound::ap_const_lv32_A = "1010";
const sc_lv<6> voicerec_classifySound::ap_const_lv6_0 = "000000";
const sc_lv<32> voicerec_classifySound::ap_const_lv32_5 = "101";
const sc_lv<4> voicerec_classifySound::ap_const_lv4_0 = "0000";
const sc_lv<3> voicerec_classifySound::ap_const_lv3_0 = "000";
const sc_lv<32> voicerec_classifySound::ap_const_lv32_6 = "110";
const sc_lv<6> voicerec_classifySound::ap_const_lv6_3F = "111111";
const sc_lv<6> voicerec_classifySound::ap_const_lv6_1 = "1";
const sc_lv<4> voicerec_classifySound::ap_const_lv4_E = "1110";
const sc_lv<4> voicerec_classifySound::ap_const_lv4_1 = "1";
const sc_lv<3> voicerec_classifySound::ap_const_lv3_4 = "100";
const sc_lv<3> voicerec_classifySound::ap_const_lv3_1 = "1";
const sc_lv<32> voicerec_classifySound::ap_const_lv32_17 = "10111";
const sc_lv<32> voicerec_classifySound::ap_const_lv32_1E = "11110";
const sc_lv<8> voicerec_classifySound::ap_const_lv8_FF = "11111111";
const sc_lv<23> voicerec_classifySound::ap_const_lv23_0 = "00000000000000000000000";
const sc_lv<5> voicerec_classifySound::ap_const_lv5_2 = "10";

voicerec_classifySound::voicerec_classifySound(sc_module_name name) : sc_module(name), mVcdFile(0) {
    output_r_U = new voicerec_classifySound_output_r("output_r_U");
    output_r_U->clk(ap_clk);
    output_r_U->reset(ap_rst);
    output_r_U->address0(output_r_address0);
    output_r_U->ce0(output_r_ce0);
    output_r_U->we0(output_r_we0);
    output_r_U->d0(output_r_d0);
    output_r_U->q0(output_r_q0);
    flatInput_U = new voicerec_classifySound_flatInput("flatInput_U");
    flatInput_U->clk(ap_clk);
    flatInput_U->reset(ap_rst);
    flatInput_U->address0(flatInput_address0);
    flatInput_U->ce0(flatInput_ce0);
    flatInput_U->we0(flatInput_we0);
    flatInput_U->d0(flatInput_d0);
    flatInput_U->q0(flatInput_q0);
    grp_voicerec_feedForward_fu_160 = new voicerec_feedForward("grp_voicerec_feedForward_fu_160");
    grp_voicerec_feedForward_fu_160->ap_clk(ap_clk);
    grp_voicerec_feedForward_fu_160->ap_rst(ap_rst);
    grp_voicerec_feedForward_fu_160->ap_start(grp_voicerec_feedForward_fu_160_ap_start);
    grp_voicerec_feedForward_fu_160->ap_done(grp_voicerec_feedForward_fu_160_ap_done);
    grp_voicerec_feedForward_fu_160->ap_idle(grp_voicerec_feedForward_fu_160_ap_idle);
    grp_voicerec_feedForward_fu_160->ap_ready(grp_voicerec_feedForward_fu_160_ap_ready);
    grp_voicerec_feedForward_fu_160->pattern_address0(grp_voicerec_feedForward_fu_160_pattern_address0);
    grp_voicerec_feedForward_fu_160->pattern_ce0(grp_voicerec_feedForward_fu_160_pattern_ce0);
    grp_voicerec_feedForward_fu_160->pattern_q0(grp_voicerec_feedForward_fu_160_pattern_q0);
    grp_voicerec_feedForward_fu_160->output_r_address0(grp_voicerec_feedForward_fu_160_output_r_address0);
    grp_voicerec_feedForward_fu_160->output_r_ce0(grp_voicerec_feedForward_fu_160_output_r_ce0);
    grp_voicerec_feedForward_fu_160->output_r_we0(grp_voicerec_feedForward_fu_160_output_r_we0);
    grp_voicerec_feedForward_fu_160->output_r_d0(grp_voicerec_feedForward_fu_160_output_r_d0);
    voicerec_fptrunc_64ns_32_1_U46 = new voicerec_fptrunc_64ns_32_1<1,1,64,32>("voicerec_fptrunc_64ns_32_1_U46");
    voicerec_fptrunc_64ns_32_1_U46->din0(tmp_1_fu_175_p0);
    voicerec_fptrunc_64ns_32_1_U46->dout(tmp_1_fu_175_p1);
    voicerec_fcmp_32ns_32ns_1_1_U47 = new voicerec_fcmp_32ns_32ns_1_1<1,1,32,32,1>("voicerec_fcmp_32ns_32ns_1_1_U47");
    voicerec_fcmp_32ns_32ns_1_1_U47->din0(tmp_10_fu_178_p0);
    voicerec_fcmp_32ns_32ns_1_1_U47->din1(tmp_10_fu_178_p1);
    voicerec_fcmp_32ns_32ns_1_1_U47->opcode(tmp_10_fu_178_opcode);
    voicerec_fcmp_32ns_32ns_1_1_U47->dout(tmp_10_fu_178_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( exitcond_i_fu_280_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( exitcond_i_fu_280_p2 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( exitcond_i_fu_280_p2 );
    sensitive << ( guess_i_reg_136 );
    sensitive << ( ap_return_preg );

    SC_METHOD(thread_ap_sig_bdd_108);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_123);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_132);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_141);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_183);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_194);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_29);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_58);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_75);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_90);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_99);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st10_fsm_9);
    sensitive << ( ap_sig_bdd_132 );

    SC_METHOD(thread_ap_sig_cseq_ST_st11_fsm_10);
    sensitive << ( ap_sig_bdd_141 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_29 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_bdd_58 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_bdd_75 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_3);
    sensitive << ( ap_sig_bdd_90 );

    SC_METHOD(thread_ap_sig_cseq_ST_st5_fsm_4);
    sensitive << ( ap_sig_bdd_99 );

    SC_METHOD(thread_ap_sig_cseq_ST_st6_fsm_5);
    sensitive << ( ap_sig_bdd_183 );

    SC_METHOD(thread_ap_sig_cseq_ST_st7_fsm_6);
    sensitive << ( ap_sig_bdd_194 );

    SC_METHOD(thread_ap_sig_cseq_ST_st8_fsm_7);
    sensitive << ( ap_sig_bdd_108 );

    SC_METHOD(thread_ap_sig_cseq_ST_st9_fsm_8);
    sensitive << ( ap_sig_bdd_123 );

    SC_METHOD(thread_exitcond1_fu_183_p2);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( i_reg_103 );

    SC_METHOD(thread_exitcond_fu_233_p2);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( j_reg_114 );

    SC_METHOD(thread_exitcond_i_fu_280_p2);
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( guess_reg_125 );

    SC_METHOD(thread_flatInput_address0);
    sensitive << ( grp_voicerec_feedForward_fu_160_pattern_address0 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( tmp_3_fu_271_p1 );

    SC_METHOD(thread_flatInput_ce0);
    sensitive << ( grp_voicerec_feedForward_fu_160_pattern_ce0 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );

    SC_METHOD(thread_flatInput_d0);
    sensitive << ( tmp_1_reg_434 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_flatInput_we0);
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_grp_voicerec_feedForward_fu_160_ap_start);
    sensitive << ( grp_voicerec_feedForward_fu_160_ap_start_ap_start_reg );

    SC_METHOD(thread_grp_voicerec_feedForward_fu_160_pattern_q0);
    sensitive << ( flatInput_q0 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );

    SC_METHOD(thread_guess_1_fu_379_p3);
    sensitive << ( guess_cast1_reg_439 );
    sensitive << ( guess_i_reg_136 );
    sensitive << ( tmp_11_fu_374_p2 );

    SC_METHOD(thread_guess_cast1_fu_276_p1);
    sensitive << ( guess_reg_125 );

    SC_METHOD(thread_i_1_fu_189_p2);
    sensitive << ( i_reg_103 );

    SC_METHOD(thread_j_1_fu_239_p2);
    sensitive << ( j_reg_114 );

    SC_METHOD(thread_j_2_fu_286_p2);
    sensitive << ( guess_reg_125 );

    SC_METHOD(thread_j_cast3_fu_229_p1);
    sensitive << ( j_reg_114 );

    SC_METHOD(thread_max_1_fu_386_p3);
    sensitive << ( max_reg_457 );
    sensitive << ( max_i_reg_148 );
    sensitive << ( tmp_11_fu_374_p2 );

    SC_METHOD(thread_max_i_to_int_fu_314_p1);
    sensitive << ( max_i_reg_148 );

    SC_METHOD(thread_max_to_int_fu_297_p1);
    sensitive << ( max_reg_457 );

    SC_METHOD(thread_notlhs6_fu_350_p2);
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( tmp_5_fu_318_p4 );

    SC_METHOD(thread_notlhs_fu_332_p2);
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( tmp_fu_300_p4 );

    SC_METHOD(thread_notrhs7_fu_356_p2);
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( tmp_6_fu_328_p1 );

    SC_METHOD(thread_notrhs_fu_338_p2);
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( tmp_4_fu_310_p1 );

    SC_METHOD(thread_output_r_address0);
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( grp_voicerec_feedForward_fu_160_output_r_address0 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( tmp_i_fu_292_p1 );

    SC_METHOD(thread_output_r_ce0);
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( grp_voicerec_feedForward_fu_160_output_r_ce0 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );

    SC_METHOD(thread_output_r_d0);
    sensitive << ( grp_voicerec_feedForward_fu_160_output_r_d0 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );

    SC_METHOD(thread_output_r_we0);
    sensitive << ( grp_voicerec_feedForward_fu_160_output_r_we0 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );

    SC_METHOD(thread_p_shl2_cast_fu_215_p1);
    sensitive << ( p_shl2_fu_207_p3 );

    SC_METHOD(thread_p_shl2_fu_207_p3);
    sensitive << ( i_reg_103 );

    SC_METHOD(thread_p_shl_cast_fu_203_p1);
    sensitive << ( p_shl_fu_195_p3 );

    SC_METHOD(thread_p_shl_fu_195_p3);
    sensitive << ( i_reg_103 );

    SC_METHOD(thread_result_addr1_cast_fu_225_p1);
    sensitive << ( tmp_8_fu_219_p2 );

    SC_METHOD(thread_result_addr2_cast_fu_254_p1);
    sensitive << ( result_addr2_fu_249_p2 );

    SC_METHOD(thread_result_addr2_fu_249_p2);
    sensitive << ( result_addr1_cast_reg_406 );
    sensitive << ( tmp_9_trn_cast_fu_245_p1 );

    SC_METHOD(thread_result_address0);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( tmp_12_fu_258_p1 );

    SC_METHOD(thread_result_ce0);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_tmp_10_fu_178_opcode);
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );

    SC_METHOD(thread_tmp_10_fu_178_p0);
    sensitive << ( max_reg_457 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );

    SC_METHOD(thread_tmp_10_fu_178_p1);
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( max_i_reg_148 );

    SC_METHOD(thread_tmp_11_fu_374_p2);
    sensitive << ( tmp_10_reg_464 );
    sensitive << ( tmp_9_fu_368_p2 );

    SC_METHOD(thread_tmp_12_fu_258_p1);
    sensitive << ( result_addr2_cast_fu_254_p1 );

    SC_METHOD(thread_tmp_1_fu_175_p0);
    sensitive << ( result_load_reg_429 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );

    SC_METHOD(thread_tmp_2_cast_fu_268_p1);
    sensitive << ( tmp_2_reg_424 );

    SC_METHOD(thread_tmp_2_fu_263_p2);
    sensitive << ( tmp_8_reg_401 );
    sensitive << ( j_cast3_fu_229_p1 );

    SC_METHOD(thread_tmp_3_fu_271_p1);
    sensitive << ( tmp_2_cast_fu_268_p1 );

    SC_METHOD(thread_tmp_4_fu_310_p1);
    sensitive << ( max_to_int_fu_297_p1 );

    SC_METHOD(thread_tmp_5_fu_318_p4);
    sensitive << ( max_i_to_int_fu_314_p1 );

    SC_METHOD(thread_tmp_6_fu_328_p1);
    sensitive << ( max_i_to_int_fu_314_p1 );

    SC_METHOD(thread_tmp_7_fu_344_p2);
    sensitive << ( notrhs_fu_338_p2 );
    sensitive << ( notlhs_fu_332_p2 );

    SC_METHOD(thread_tmp_8_fu_219_p2);
    sensitive << ( p_shl_cast_fu_203_p1 );
    sensitive << ( p_shl2_cast_fu_215_p1 );

    SC_METHOD(thread_tmp_9_fu_368_p2);
    sensitive << ( tmp_7_fu_344_p2 );
    sensitive << ( tmp_s_fu_362_p2 );

    SC_METHOD(thread_tmp_9_trn_cast_fu_245_p1);
    sensitive << ( j_reg_114 );

    SC_METHOD(thread_tmp_fu_300_p4);
    sensitive << ( max_to_int_fu_297_p1 );

    SC_METHOD(thread_tmp_i_fu_292_p1);
    sensitive << ( guess_reg_125 );

    SC_METHOD(thread_tmp_s_fu_362_p2);
    sensitive << ( notrhs7_fu_356_p2 );
    sensitive << ( notlhs6_fu_350_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond1_fu_183_p2 );
    sensitive << ( exitcond_fu_233_p2 );
    sensitive << ( exitcond_i_fu_280_p2 );
    sensitive << ( grp_voicerec_feedForward_fu_160_ap_done );

    ap_CS_fsm = "00000000001";
    grp_voicerec_feedForward_fu_160_ap_start_ap_start_reg = SC_LOGIC_0;
    ap_return_preg = "00000000000000000000000000000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "voicerec_classifySound_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, result_address0, "(port)result_address0");
    sc_trace(mVcdFile, result_ce0, "(port)result_ce0");
    sc_trace(mVcdFile, result_q0, "(port)result_q0");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_29, "ap_sig_bdd_29");
    sc_trace(mVcdFile, output_r_address0, "output_r_address0");
    sc_trace(mVcdFile, output_r_ce0, "output_r_ce0");
    sc_trace(mVcdFile, output_r_we0, "output_r_we0");
    sc_trace(mVcdFile, output_r_d0, "output_r_d0");
    sc_trace(mVcdFile, output_r_q0, "output_r_q0");
    sc_trace(mVcdFile, i_1_fu_189_p2, "i_1_fu_189_p2");
    sc_trace(mVcdFile, i_1_reg_396, "i_1_reg_396");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_58, "ap_sig_bdd_58");
    sc_trace(mVcdFile, tmp_8_fu_219_p2, "tmp_8_fu_219_p2");
    sc_trace(mVcdFile, tmp_8_reg_401, "tmp_8_reg_401");
    sc_trace(mVcdFile, exitcond1_fu_183_p2, "exitcond1_fu_183_p2");
    sc_trace(mVcdFile, result_addr1_cast_fu_225_p1, "result_addr1_cast_fu_225_p1");
    sc_trace(mVcdFile, result_addr1_cast_reg_406, "result_addr1_cast_reg_406");
    sc_trace(mVcdFile, j_1_fu_239_p2, "j_1_fu_239_p2");
    sc_trace(mVcdFile, j_1_reg_414, "j_1_reg_414");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_bdd_75, "ap_sig_bdd_75");
    sc_trace(mVcdFile, exitcond_fu_233_p2, "exitcond_fu_233_p2");
    sc_trace(mVcdFile, tmp_2_fu_263_p2, "tmp_2_fu_263_p2");
    sc_trace(mVcdFile, tmp_2_reg_424, "tmp_2_reg_424");
    sc_trace(mVcdFile, result_load_reg_429, "result_load_reg_429");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_3, "ap_sig_cseq_ST_st4_fsm_3");
    sc_trace(mVcdFile, ap_sig_bdd_90, "ap_sig_bdd_90");
    sc_trace(mVcdFile, tmp_1_fu_175_p1, "tmp_1_fu_175_p1");
    sc_trace(mVcdFile, tmp_1_reg_434, "tmp_1_reg_434");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st5_fsm_4, "ap_sig_cseq_ST_st5_fsm_4");
    sc_trace(mVcdFile, ap_sig_bdd_99, "ap_sig_bdd_99");
    sc_trace(mVcdFile, guess_cast1_fu_276_p1, "guess_cast1_fu_276_p1");
    sc_trace(mVcdFile, guess_cast1_reg_439, "guess_cast1_reg_439");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st8_fsm_7, "ap_sig_cseq_ST_st8_fsm_7");
    sc_trace(mVcdFile, ap_sig_bdd_108, "ap_sig_bdd_108");
    sc_trace(mVcdFile, j_2_fu_286_p2, "j_2_fu_286_p2");
    sc_trace(mVcdFile, j_2_reg_447, "j_2_reg_447");
    sc_trace(mVcdFile, exitcond_i_fu_280_p2, "exitcond_i_fu_280_p2");
    sc_trace(mVcdFile, max_reg_457, "max_reg_457");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st9_fsm_8, "ap_sig_cseq_ST_st9_fsm_8");
    sc_trace(mVcdFile, ap_sig_bdd_123, "ap_sig_bdd_123");
    sc_trace(mVcdFile, tmp_10_fu_178_p2, "tmp_10_fu_178_p2");
    sc_trace(mVcdFile, tmp_10_reg_464, "tmp_10_reg_464");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st10_fsm_9, "ap_sig_cseq_ST_st10_fsm_9");
    sc_trace(mVcdFile, ap_sig_bdd_132, "ap_sig_bdd_132");
    sc_trace(mVcdFile, guess_1_fu_379_p3, "guess_1_fu_379_p3");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st11_fsm_10, "ap_sig_cseq_ST_st11_fsm_10");
    sc_trace(mVcdFile, ap_sig_bdd_141, "ap_sig_bdd_141");
    sc_trace(mVcdFile, max_1_fu_386_p3, "max_1_fu_386_p3");
    sc_trace(mVcdFile, flatInput_address0, "flatInput_address0");
    sc_trace(mVcdFile, flatInput_ce0, "flatInput_ce0");
    sc_trace(mVcdFile, flatInput_we0, "flatInput_we0");
    sc_trace(mVcdFile, flatInput_d0, "flatInput_d0");
    sc_trace(mVcdFile, flatInput_q0, "flatInput_q0");
    sc_trace(mVcdFile, grp_voicerec_feedForward_fu_160_ap_start, "grp_voicerec_feedForward_fu_160_ap_start");
    sc_trace(mVcdFile, grp_voicerec_feedForward_fu_160_ap_done, "grp_voicerec_feedForward_fu_160_ap_done");
    sc_trace(mVcdFile, grp_voicerec_feedForward_fu_160_ap_idle, "grp_voicerec_feedForward_fu_160_ap_idle");
    sc_trace(mVcdFile, grp_voicerec_feedForward_fu_160_ap_ready, "grp_voicerec_feedForward_fu_160_ap_ready");
    sc_trace(mVcdFile, grp_voicerec_feedForward_fu_160_pattern_address0, "grp_voicerec_feedForward_fu_160_pattern_address0");
    sc_trace(mVcdFile, grp_voicerec_feedForward_fu_160_pattern_ce0, "grp_voicerec_feedForward_fu_160_pattern_ce0");
    sc_trace(mVcdFile, grp_voicerec_feedForward_fu_160_pattern_q0, "grp_voicerec_feedForward_fu_160_pattern_q0");
    sc_trace(mVcdFile, grp_voicerec_feedForward_fu_160_output_r_address0, "grp_voicerec_feedForward_fu_160_output_r_address0");
    sc_trace(mVcdFile, grp_voicerec_feedForward_fu_160_output_r_ce0, "grp_voicerec_feedForward_fu_160_output_r_ce0");
    sc_trace(mVcdFile, grp_voicerec_feedForward_fu_160_output_r_we0, "grp_voicerec_feedForward_fu_160_output_r_we0");
    sc_trace(mVcdFile, grp_voicerec_feedForward_fu_160_output_r_d0, "grp_voicerec_feedForward_fu_160_output_r_d0");
    sc_trace(mVcdFile, i_reg_103, "i_reg_103");
    sc_trace(mVcdFile, j_reg_114, "j_reg_114");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st6_fsm_5, "ap_sig_cseq_ST_st6_fsm_5");
    sc_trace(mVcdFile, ap_sig_bdd_183, "ap_sig_bdd_183");
    sc_trace(mVcdFile, guess_reg_125, "guess_reg_125");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st7_fsm_6, "ap_sig_cseq_ST_st7_fsm_6");
    sc_trace(mVcdFile, ap_sig_bdd_194, "ap_sig_bdd_194");
    sc_trace(mVcdFile, guess_i_reg_136, "guess_i_reg_136");
    sc_trace(mVcdFile, max_i_reg_148, "max_i_reg_148");
    sc_trace(mVcdFile, grp_voicerec_feedForward_fu_160_ap_start_ap_start_reg, "grp_voicerec_feedForward_fu_160_ap_start_ap_start_reg");
    sc_trace(mVcdFile, tmp_12_fu_258_p1, "tmp_12_fu_258_p1");
    sc_trace(mVcdFile, tmp_3_fu_271_p1, "tmp_3_fu_271_p1");
    sc_trace(mVcdFile, tmp_i_fu_292_p1, "tmp_i_fu_292_p1");
    sc_trace(mVcdFile, tmp_1_fu_175_p0, "tmp_1_fu_175_p0");
    sc_trace(mVcdFile, tmp_10_fu_178_p0, "tmp_10_fu_178_p0");
    sc_trace(mVcdFile, tmp_10_fu_178_p1, "tmp_10_fu_178_p1");
    sc_trace(mVcdFile, p_shl_fu_195_p3, "p_shl_fu_195_p3");
    sc_trace(mVcdFile, p_shl2_fu_207_p3, "p_shl2_fu_207_p3");
    sc_trace(mVcdFile, p_shl_cast_fu_203_p1, "p_shl_cast_fu_203_p1");
    sc_trace(mVcdFile, p_shl2_cast_fu_215_p1, "p_shl2_cast_fu_215_p1");
    sc_trace(mVcdFile, tmp_9_trn_cast_fu_245_p1, "tmp_9_trn_cast_fu_245_p1");
    sc_trace(mVcdFile, result_addr2_fu_249_p2, "result_addr2_fu_249_p2");
    sc_trace(mVcdFile, result_addr2_cast_fu_254_p1, "result_addr2_cast_fu_254_p1");
    sc_trace(mVcdFile, j_cast3_fu_229_p1, "j_cast3_fu_229_p1");
    sc_trace(mVcdFile, tmp_2_cast_fu_268_p1, "tmp_2_cast_fu_268_p1");
    sc_trace(mVcdFile, max_to_int_fu_297_p1, "max_to_int_fu_297_p1");
    sc_trace(mVcdFile, max_i_to_int_fu_314_p1, "max_i_to_int_fu_314_p1");
    sc_trace(mVcdFile, tmp_fu_300_p4, "tmp_fu_300_p4");
    sc_trace(mVcdFile, tmp_4_fu_310_p1, "tmp_4_fu_310_p1");
    sc_trace(mVcdFile, notrhs_fu_338_p2, "notrhs_fu_338_p2");
    sc_trace(mVcdFile, notlhs_fu_332_p2, "notlhs_fu_332_p2");
    sc_trace(mVcdFile, tmp_5_fu_318_p4, "tmp_5_fu_318_p4");
    sc_trace(mVcdFile, tmp_6_fu_328_p1, "tmp_6_fu_328_p1");
    sc_trace(mVcdFile, notrhs7_fu_356_p2, "notrhs7_fu_356_p2");
    sc_trace(mVcdFile, notlhs6_fu_350_p2, "notlhs6_fu_350_p2");
    sc_trace(mVcdFile, tmp_7_fu_344_p2, "tmp_7_fu_344_p2");
    sc_trace(mVcdFile, tmp_s_fu_362_p2, "tmp_s_fu_362_p2");
    sc_trace(mVcdFile, tmp_9_fu_368_p2, "tmp_9_fu_368_p2");
    sc_trace(mVcdFile, tmp_11_fu_374_p2, "tmp_11_fu_374_p2");
    sc_trace(mVcdFile, tmp_10_fu_178_opcode, "tmp_10_fu_178_opcode");
    sc_trace(mVcdFile, ap_return_preg, "ap_return_preg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

voicerec_classifySound::~voicerec_classifySound() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete output_r_U;
    delete flatInput_U;
    delete grp_voicerec_feedForward_fu_160;
    delete voicerec_fptrunc_64ns_32_1_U46;
    delete voicerec_fcmp_32ns_32ns_1_1_U47;
}

void voicerec_classifySound::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_preg = ap_const_lv32_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) && 
             !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_fu_280_p2.read()))) {
            ap_return_preg = guess_i_reg_136.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_voicerec_feedForward_fu_160_ap_start_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
             !esl_seteq<1,1,1>(exitcond1_fu_183_p2.read(), ap_const_lv1_0))) {
            grp_voicerec_feedForward_fu_160_ap_start_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_voicerec_feedForward_fu_160_ap_ready.read())) {
            grp_voicerec_feedForward_fu_160_ap_start_ap_start_reg = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read())) {
        guess_reg_125 = j_2_reg_447.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
                !esl_seteq<1,1,1>(ap_const_logic_0, grp_voicerec_feedForward_fu_160_ap_done.read()))) {
        guess_reg_125 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_233_p2.read()))) {
        i_reg_103 = i_1_reg_396.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        i_reg_103 = ap_const_lv6_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond1_fu_183_p2.read(), ap_const_lv1_0))) {
        j_reg_114 = ap_const_lv4_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        j_reg_114 = j_1_reg_414.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read())) {
        max_i_reg_148 = max_1_fu_386_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
                !esl_seteq<1,1,1>(ap_const_logic_0, grp_voicerec_feedForward_fu_160_ap_done.read()))) {
        max_i_reg_148 = ap_const_lv32_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        guess_cast1_reg_439 = guess_cast1_fu_276_p1.read();
        j_2_reg_447 = j_2_fu_286_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read())) {
        guess_i_reg_136 = guess_1_fu_379_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        i_1_reg_396 = i_1_fu_189_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        j_1_reg_414 = j_1_fu_239_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
        max_reg_457 = output_r_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && esl_seteq<1,1,1>(exitcond1_fu_183_p2.read(), ap_const_lv1_0))) {
        result_addr1_cast_reg_406 = result_addr1_cast_fu_225_p1.read();
        tmp_8_reg_401 = tmp_8_fu_219_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        result_load_reg_429 = result_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        tmp_10_reg_464 = tmp_10_fu_178_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        tmp_1_reg_434 = tmp_1_fu_175_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_233_p2.read()))) {
        tmp_2_reg_424 = tmp_2_fu_263_p2.read();
    }
}

void voicerec_classifySound::thread_ap_done() {
    if (((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_fu_280_p2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void voicerec_classifySound::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void voicerec_classifySound::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_fu_280_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void voicerec_classifySound::thread_ap_return() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_fu_280_p2.read()))) {
        ap_return = guess_i_reg_136.read();
    } else {
        ap_return = ap_return_preg.read();
    }
}

void voicerec_classifySound::thread_ap_sig_bdd_108() {
    ap_sig_bdd_108 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(7, 7));
}

void voicerec_classifySound::thread_ap_sig_bdd_123() {
    ap_sig_bdd_123 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(8, 8));
}

void voicerec_classifySound::thread_ap_sig_bdd_132() {
    ap_sig_bdd_132 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(9, 9));
}

void voicerec_classifySound::thread_ap_sig_bdd_141() {
    ap_sig_bdd_141 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(10, 10));
}

void voicerec_classifySound::thread_ap_sig_bdd_183() {
    ap_sig_bdd_183 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(5, 5));
}

void voicerec_classifySound::thread_ap_sig_bdd_194() {
    ap_sig_bdd_194 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(6, 6));
}

void voicerec_classifySound::thread_ap_sig_bdd_29() {
    ap_sig_bdd_29 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void voicerec_classifySound::thread_ap_sig_bdd_58() {
    ap_sig_bdd_58 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void voicerec_classifySound::thread_ap_sig_bdd_75() {
    ap_sig_bdd_75 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void voicerec_classifySound::thread_ap_sig_bdd_90() {
    ap_sig_bdd_90 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void voicerec_classifySound::thread_ap_sig_bdd_99() {
    ap_sig_bdd_99 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(4, 4));
}

void voicerec_classifySound::thread_ap_sig_cseq_ST_st10_fsm_9() {
    if (ap_sig_bdd_132.read()) {
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_0;
    }
}

void voicerec_classifySound::thread_ap_sig_cseq_ST_st11_fsm_10() {
    if (ap_sig_bdd_141.read()) {
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_0;
    }
}

void voicerec_classifySound::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_29.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void voicerec_classifySound::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_bdd_58.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void voicerec_classifySound::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_bdd_75.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void voicerec_classifySound::thread_ap_sig_cseq_ST_st4_fsm_3() {
    if (ap_sig_bdd_90.read()) {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    }
}

void voicerec_classifySound::thread_ap_sig_cseq_ST_st5_fsm_4() {
    if (ap_sig_bdd_99.read()) {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    }
}

void voicerec_classifySound::thread_ap_sig_cseq_ST_st6_fsm_5() {
    if (ap_sig_bdd_183.read()) {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    }
}

void voicerec_classifySound::thread_ap_sig_cseq_ST_st7_fsm_6() {
    if (ap_sig_bdd_194.read()) {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    }
}

void voicerec_classifySound::thread_ap_sig_cseq_ST_st8_fsm_7() {
    if (ap_sig_bdd_108.read()) {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_0;
    }
}

void voicerec_classifySound::thread_ap_sig_cseq_ST_st9_fsm_8() {
    if (ap_sig_bdd_123.read()) {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_0;
    }
}

void voicerec_classifySound::thread_exitcond1_fu_183_p2() {
    exitcond1_fu_183_p2 = (!i_reg_103.read().is_01() || !ap_const_lv6_3F.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_103.read() == ap_const_lv6_3F);
}

void voicerec_classifySound::thread_exitcond_fu_233_p2() {
    exitcond_fu_233_p2 = (!j_reg_114.read().is_01() || !ap_const_lv4_E.is_01())? sc_lv<1>(): sc_lv<1>(j_reg_114.read() == ap_const_lv4_E);
}

void voicerec_classifySound::thread_exitcond_i_fu_280_p2() {
    exitcond_i_fu_280_p2 = (!guess_reg_125.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(guess_reg_125.read() == ap_const_lv3_4);
}

void voicerec_classifySound::thread_flatInput_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        flatInput_address0 =  (sc_lv<10>) (tmp_3_fu_271_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        flatInput_address0 = grp_voicerec_feedForward_fu_160_pattern_address0.read();
    } else {
        flatInput_address0 = "XXXXXXXXXX";
    }
}

void voicerec_classifySound::thread_flatInput_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        flatInput_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        flatInput_ce0 = grp_voicerec_feedForward_fu_160_pattern_ce0.read();
    } else {
        flatInput_ce0 = ap_const_logic_0;
    }
}

void voicerec_classifySound::thread_flatInput_d0() {
    flatInput_d0 = tmp_1_reg_434.read();
}

void voicerec_classifySound::thread_flatInput_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()))) {
        flatInput_we0 = ap_const_logic_1;
    } else {
        flatInput_we0 = ap_const_logic_0;
    }
}

void voicerec_classifySound::thread_grp_voicerec_feedForward_fu_160_ap_start() {
    grp_voicerec_feedForward_fu_160_ap_start = grp_voicerec_feedForward_fu_160_ap_start_ap_start_reg.read();
}

void voicerec_classifySound::thread_grp_voicerec_feedForward_fu_160_pattern_q0() {
    grp_voicerec_feedForward_fu_160_pattern_q0 = flatInput_q0.read();
}

void voicerec_classifySound::thread_guess_1_fu_379_p3() {
    guess_1_fu_379_p3 = (!tmp_11_fu_374_p2.read()[0].is_01())? sc_lv<32>(): ((tmp_11_fu_374_p2.read()[0].to_bool())? guess_cast1_reg_439.read(): guess_i_reg_136.read());
}

void voicerec_classifySound::thread_guess_cast1_fu_276_p1() {
    guess_cast1_fu_276_p1 = esl_zext<32,3>(guess_reg_125.read());
}

void voicerec_classifySound::thread_i_1_fu_189_p2() {
    i_1_fu_189_p2 = (!i_reg_103.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(i_reg_103.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void voicerec_classifySound::thread_j_1_fu_239_p2() {
    j_1_fu_239_p2 = (!j_reg_114.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(j_reg_114.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void voicerec_classifySound::thread_j_2_fu_286_p2() {
    j_2_fu_286_p2 = (!guess_reg_125.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(guess_reg_125.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void voicerec_classifySound::thread_j_cast3_fu_229_p1() {
    j_cast3_fu_229_p1 = esl_zext<11,4>(j_reg_114.read());
}

void voicerec_classifySound::thread_max_1_fu_386_p3() {
    max_1_fu_386_p3 = (!tmp_11_fu_374_p2.read()[0].is_01())? sc_lv<32>(): ((tmp_11_fu_374_p2.read()[0].to_bool())? max_reg_457.read(): max_i_reg_148.read());
}

void voicerec_classifySound::thread_max_i_to_int_fu_314_p1() {
    max_i_to_int_fu_314_p1 = max_i_reg_148.read();
}

void voicerec_classifySound::thread_max_to_int_fu_297_p1() {
    max_to_int_fu_297_p1 = max_reg_457.read();
}

void voicerec_classifySound::thread_notlhs6_fu_350_p2() {
    notlhs6_fu_350_p2 = (!tmp_5_fu_318_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_5_fu_318_p4.read() != ap_const_lv8_FF);
}

void voicerec_classifySound::thread_notlhs_fu_332_p2() {
    notlhs_fu_332_p2 = (!tmp_fu_300_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_fu_300_p4.read() != ap_const_lv8_FF);
}

void voicerec_classifySound::thread_notrhs7_fu_356_p2() {
    notrhs7_fu_356_p2 = (!tmp_6_fu_328_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_6_fu_328_p1.read() == ap_const_lv23_0);
}

void voicerec_classifySound::thread_notrhs_fu_338_p2() {
    notrhs_fu_338_p2 = (!tmp_4_fu_310_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_4_fu_310_p1.read() == ap_const_lv23_0);
}

void voicerec_classifySound::thread_output_r_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        output_r_address0 =  (sc_lv<2>) (tmp_i_fu_292_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        output_r_address0 = grp_voicerec_feedForward_fu_160_output_r_address0.read();
    } else {
        output_r_address0 =  (sc_lv<2>) ("XX");
    }
}

void voicerec_classifySound::thread_output_r_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        output_r_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        output_r_ce0 = grp_voicerec_feedForward_fu_160_output_r_ce0.read();
    } else {
        output_r_ce0 = ap_const_logic_0;
    }
}

void voicerec_classifySound::thread_output_r_d0() {
    output_r_d0 = grp_voicerec_feedForward_fu_160_output_r_d0.read();
}

void voicerec_classifySound::thread_output_r_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        output_r_we0 = grp_voicerec_feedForward_fu_160_output_r_we0.read();
    } else {
        output_r_we0 = ap_const_logic_0;
    }
}

void voicerec_classifySound::thread_p_shl2_cast_fu_215_p1() {
    p_shl2_cast_fu_215_p1 = esl_zext<11,7>(p_shl2_fu_207_p3.read());
}

void voicerec_classifySound::thread_p_shl2_fu_207_p3() {
    p_shl2_fu_207_p3 = esl_concat<6,1>(i_reg_103.read(), ap_const_lv1_0);
}

void voicerec_classifySound::thread_p_shl_cast_fu_203_p1() {
    p_shl_cast_fu_203_p1 = esl_zext<11,10>(p_shl_fu_195_p3.read());
}

void voicerec_classifySound::thread_p_shl_fu_195_p3() {
    p_shl_fu_195_p3 = esl_concat<6,4>(i_reg_103.read(), ap_const_lv4_0);
}

void voicerec_classifySound::thread_result_addr1_cast_fu_225_p1() {
    result_addr1_cast_fu_225_p1 = esl_sext<12,11>(tmp_8_fu_219_p2.read());
}

void voicerec_classifySound::thread_result_addr2_cast_fu_254_p1() {
    result_addr2_cast_fu_254_p1 = esl_sext<32,12>(result_addr2_fu_249_p2.read());
}

void voicerec_classifySound::thread_result_addr2_fu_249_p2() {
    result_addr2_fu_249_p2 = (!tmp_9_trn_cast_fu_245_p1.read().is_01() || !result_addr1_cast_reg_406.read().is_01())? sc_lv<12>(): (sc_biguint<12>(tmp_9_trn_cast_fu_245_p1.read()) + sc_bigint<12>(result_addr1_cast_reg_406.read()));
}

void voicerec_classifySound::thread_result_address0() {
    result_address0 =  (sc_lv<10>) (tmp_12_fu_258_p1.read());
}

void voicerec_classifySound::thread_result_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        result_ce0 = ap_const_logic_1;
    } else {
        result_ce0 = ap_const_logic_0;
    }
}

void voicerec_classifySound::thread_tmp_10_fu_178_opcode() {
    tmp_10_fu_178_opcode = ap_const_lv5_2;
}

void voicerec_classifySound::thread_tmp_10_fu_178_p0() {
    tmp_10_fu_178_p0 = max_reg_457.read();
}

void voicerec_classifySound::thread_tmp_10_fu_178_p1() {
    tmp_10_fu_178_p1 = max_i_reg_148.read();
}

void voicerec_classifySound::thread_tmp_11_fu_374_p2() {
    tmp_11_fu_374_p2 = (tmp_9_fu_368_p2.read() & tmp_10_reg_464.read());
}

void voicerec_classifySound::thread_tmp_12_fu_258_p1() {
    tmp_12_fu_258_p1 = esl_zext<64,32>(result_addr2_cast_fu_254_p1.read());
}

void voicerec_classifySound::thread_tmp_1_fu_175_p0() {
    tmp_1_fu_175_p0 = result_load_reg_429.read();
}

void voicerec_classifySound::thread_tmp_2_cast_fu_268_p1() {
    tmp_2_cast_fu_268_p1 = esl_sext<32,11>(tmp_2_reg_424.read());
}

void voicerec_classifySound::thread_tmp_2_fu_263_p2() {
    tmp_2_fu_263_p2 = (!tmp_8_reg_401.read().is_01() || !j_cast3_fu_229_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(tmp_8_reg_401.read()) + sc_biguint<11>(j_cast3_fu_229_p1.read()));
}

void voicerec_classifySound::thread_tmp_3_fu_271_p1() {
    tmp_3_fu_271_p1 = esl_zext<64,32>(tmp_2_cast_fu_268_p1.read());
}

void voicerec_classifySound::thread_tmp_4_fu_310_p1() {
    tmp_4_fu_310_p1 = max_to_int_fu_297_p1.read().range(23-1, 0);
}

void voicerec_classifySound::thread_tmp_5_fu_318_p4() {
    tmp_5_fu_318_p4 = max_i_to_int_fu_314_p1.read().range(30, 23);
}

void voicerec_classifySound::thread_tmp_6_fu_328_p1() {
    tmp_6_fu_328_p1 = max_i_to_int_fu_314_p1.read().range(23-1, 0);
}

void voicerec_classifySound::thread_tmp_7_fu_344_p2() {
    tmp_7_fu_344_p2 = (notrhs_fu_338_p2.read() | notlhs_fu_332_p2.read());
}

void voicerec_classifySound::thread_tmp_8_fu_219_p2() {
    tmp_8_fu_219_p2 = (!p_shl_cast_fu_203_p1.read().is_01() || !p_shl2_cast_fu_215_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(p_shl_cast_fu_203_p1.read()) - sc_biguint<11>(p_shl2_cast_fu_215_p1.read()));
}

void voicerec_classifySound::thread_tmp_9_fu_368_p2() {
    tmp_9_fu_368_p2 = (tmp_7_fu_344_p2.read() & tmp_s_fu_362_p2.read());
}

void voicerec_classifySound::thread_tmp_9_trn_cast_fu_245_p1() {
    tmp_9_trn_cast_fu_245_p1 = esl_zext<12,4>(j_reg_114.read());
}

void voicerec_classifySound::thread_tmp_fu_300_p4() {
    tmp_fu_300_p4 = max_to_int_fu_297_p1.read().range(30, 23);
}

void voicerec_classifySound::thread_tmp_i_fu_292_p1() {
    tmp_i_fu_292_p1 = esl_zext<64,3>(guess_reg_125.read());
}

void voicerec_classifySound::thread_tmp_s_fu_362_p2() {
    tmp_s_fu_362_p2 = (notrhs7_fu_356_p2.read() | notlhs6_fu_350_p2.read());
}

void voicerec_classifySound::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (esl_seteq<1,1,1>(exitcond1_fu_183_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            } else {
                ap_NS_fsm = ap_ST_st7_fsm_6;
            }
            break;
        case 4 : 
            if (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_233_p2.read())) {
                ap_NS_fsm = ap_ST_st4_fsm_3;
            } else {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_st5_fsm_4;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_st6_fsm_5;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_st3_fsm_2;
            break;
        case 64 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_0, grp_voicerec_feedForward_fu_160_ap_done.read())) {
                ap_NS_fsm = ap_ST_st8_fsm_7;
            } else {
                ap_NS_fsm = ap_ST_st7_fsm_6;
            }
            break;
        case 128 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_fu_280_p2.read())) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st9_fsm_8;
            }
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_st10_fsm_9;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_st11_fsm_10;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_st8_fsm_7;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<11>) ("XXXXXXXXXXX");
            break;
    }
}

}

