// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "voicerec.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic voicerec::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic voicerec::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<5> voicerec::ap_ST_st1_fsm_0 = "1";
const sc_lv<5> voicerec::ap_ST_st2_fsm_1 = "10";
const sc_lv<5> voicerec::ap_ST_st3_fsm_2 = "100";
const sc_lv<5> voicerec::ap_ST_st4_fsm_3 = "1000";
const sc_lv<5> voicerec::ap_ST_st5_fsm_4 = "10000";
const sc_lv<32> voicerec::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> voicerec::ap_const_lv1_1 = "1";
const sc_lv<32> voicerec::ap_const_lv32_1 = "1";
const sc_lv<32> voicerec::ap_const_lv32_2 = "10";
const sc_lv<1> voicerec::ap_const_lv1_0 = "0";
const sc_lv<32> voicerec::ap_const_lv32_3 = "11";
const sc_lv<32> voicerec::ap_const_lv32_4 = "100";
const sc_lv<32> voicerec::ap_const_lv32_1F = "11111";
const sc_lv<32> voicerec::ap_const_lv32_1F40 = "1111101000000";

voicerec::voicerec(sc_module_name name) : sc_module(name), mVcdFile(0) {
    result_U = new voicerec_result("result_U");
    result_U->clk(ap_clk);
    result_U->reset(ap_rst);
    result_U->address0(result_address0);
    result_U->ce0(result_ce0);
    result_U->we0(result_we0);
    result_U->d0(result_d0);
    result_U->q0(result_q0);
    outSound_U = new voicerec_outSound("outSound_U");
    outSound_U->clk(ap_clk);
    outSound_U->reset(ap_rst);
    outSound_U->address0(outSound_address0);
    outSound_U->ce0(outSound_ce0);
    outSound_U->we0(outSound_we0);
    outSound_U->d0(outSound_d0);
    outSound_U->q0(outSound_q0);
    grp_voicerec_processChunk_fu_92 = new voicerec_processChunk("grp_voicerec_processChunk_fu_92");
    grp_voicerec_processChunk_fu_92->ap_clk(ap_clk);
    grp_voicerec_processChunk_fu_92->ap_rst(ap_rst);
    grp_voicerec_processChunk_fu_92->ap_start(grp_voicerec_processChunk_fu_92_ap_start);
    grp_voicerec_processChunk_fu_92->ap_done(grp_voicerec_processChunk_fu_92_ap_done);
    grp_voicerec_processChunk_fu_92->ap_idle(grp_voicerec_processChunk_fu_92_ap_idle);
    grp_voicerec_processChunk_fu_92->ap_ready(grp_voicerec_processChunk_fu_92_ap_ready);
    grp_voicerec_processChunk_fu_92->sp(grp_voicerec_processChunk_fu_92_sp);
    grp_voicerec_processChunk_fu_92->np(grp_voicerec_processChunk_fu_92_np);
    grp_voicerec_processChunk_fu_92->ret_address0(grp_voicerec_processChunk_fu_92_ret_address0);
    grp_voicerec_processChunk_fu_92->ret_ce0(grp_voicerec_processChunk_fu_92_ret_ce0);
    grp_voicerec_processChunk_fu_92->ret_we0(grp_voicerec_processChunk_fu_92_ret_we0);
    grp_voicerec_processChunk_fu_92->ret_d0(grp_voicerec_processChunk_fu_92_ret_d0);
    grp_voicerec_processChunk_fu_92->tmp_122(grp_voicerec_processChunk_fu_92_tmp_122);
    grp_voicerec_processChunk_fu_92->inputSound_address0(grp_voicerec_processChunk_fu_92_inputSound_address0);
    grp_voicerec_processChunk_fu_92->inputSound_ce0(grp_voicerec_processChunk_fu_92_inputSound_ce0);
    grp_voicerec_processChunk_fu_92->inputSound_q0(grp_voicerec_processChunk_fu_92_inputSound_q0);
    grp_voicerec_classifySound_fu_118 = new voicerec_classifySound("grp_voicerec_classifySound_fu_118");
    grp_voicerec_classifySound_fu_118->ap_clk(ap_clk);
    grp_voicerec_classifySound_fu_118->ap_rst(ap_rst);
    grp_voicerec_classifySound_fu_118->ap_start(grp_voicerec_classifySound_fu_118_ap_start);
    grp_voicerec_classifySound_fu_118->ap_done(grp_voicerec_classifySound_fu_118_ap_done);
    grp_voicerec_classifySound_fu_118->ap_idle(grp_voicerec_classifySound_fu_118_ap_idle);
    grp_voicerec_classifySound_fu_118->ap_ready(grp_voicerec_classifySound_fu_118_ap_ready);
    grp_voicerec_classifySound_fu_118->result_address0(grp_voicerec_classifySound_fu_118_result_address0);
    grp_voicerec_classifySound_fu_118->result_ce0(grp_voicerec_classifySound_fu_118_result_ce0);
    grp_voicerec_classifySound_fu_118->result_q0(grp_voicerec_classifySound_fu_118_result_q0);
    grp_voicerec_classifySound_fu_118->ap_return(grp_voicerec_classifySound_fu_118_ap_return);
    grp_voicerec_preprocessSound_fu_134 = new voicerec_preprocessSound("grp_voicerec_preprocessSound_fu_134");
    grp_voicerec_preprocessSound_fu_134->ap_clk(ap_clk);
    grp_voicerec_preprocessSound_fu_134->ap_rst(ap_rst);
    grp_voicerec_preprocessSound_fu_134->ap_start(grp_voicerec_preprocessSound_fu_134_ap_start);
    grp_voicerec_preprocessSound_fu_134->ap_done(grp_voicerec_preprocessSound_fu_134_ap_done);
    grp_voicerec_preprocessSound_fu_134->ap_idle(grp_voicerec_preprocessSound_fu_134_ap_idle);
    grp_voicerec_preprocessSound_fu_134->ap_ready(grp_voicerec_preprocessSound_fu_134_ap_ready);
    grp_voicerec_preprocessSound_fu_134->inSound_address0(grp_voicerec_preprocessSound_fu_134_inSound_address0);
    grp_voicerec_preprocessSound_fu_134->inSound_ce0(grp_voicerec_preprocessSound_fu_134_inSound_ce0);
    grp_voicerec_preprocessSound_fu_134->inSound_we0(grp_voicerec_preprocessSound_fu_134_inSound_we0);
    grp_voicerec_preprocessSound_fu_134->inSound_d0(grp_voicerec_preprocessSound_fu_134_inSound_d0);
    grp_voicerec_preprocessSound_fu_134->inSound_q0(grp_voicerec_preprocessSound_fu_134_inSound_q0);
    grp_voicerec_preprocessSound_fu_134->outSound_address0(grp_voicerec_preprocessSound_fu_134_outSound_address0);
    grp_voicerec_preprocessSound_fu_134->outSound_ce0(grp_voicerec_preprocessSound_fu_134_outSound_ce0);
    grp_voicerec_preprocessSound_fu_134->outSound_we0(grp_voicerec_preprocessSound_fu_134_outSound_we0);
    grp_voicerec_preprocessSound_fu_134->outSound_d0(grp_voicerec_preprocessSound_fu_134_outSound_d0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( grp_voicerec_classifySound_fu_118_ap_done );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( grp_voicerec_classifySound_fu_118_ap_done );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );

    SC_METHOD(thread_ap_return);
    sensitive << ( grp_voicerec_classifySound_fu_118_ap_done );
    sensitive << ( grp_voicerec_classifySound_fu_118_ap_return );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );

    SC_METHOD(thread_ap_sig_bdd_136);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_21);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_234);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_55);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_70);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_21 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_bdd_55 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_bdd_70 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_3);
    sensitive << ( ap_sig_bdd_136 );

    SC_METHOD(thread_ap_sig_cseq_ST_st5_fsm_4);
    sensitive << ( ap_sig_bdd_234 );

    SC_METHOD(thread_grp_voicerec_classifySound_fu_118_ap_start);
    sensitive << ( grp_voicerec_classifySound_fu_118_ap_start_ap_start_reg );

    SC_METHOD(thread_grp_voicerec_classifySound_fu_118_result_q0);
    sensitive << ( result_q0 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );

    SC_METHOD(thread_grp_voicerec_preprocessSound_fu_134_ap_start);
    sensitive << ( grp_voicerec_preprocessSound_fu_134_ap_start_ap_start_reg );

    SC_METHOD(thread_grp_voicerec_preprocessSound_fu_134_inSound_q0);
    sensitive << ( inSound_q0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_voicerec_processChunk_fu_92_ap_start);
    sensitive << ( grp_voicerec_processChunk_fu_92_ap_start_ap_start_reg );

    SC_METHOD(thread_grp_voicerec_processChunk_fu_92_inputSound_q0);
    sensitive << ( outSound_q0 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_grp_voicerec_processChunk_fu_92_np);
    sensitive << ( np );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_grp_voicerec_processChunk_fu_92_sp);
    sensitive << ( i_reg_68 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_grp_voicerec_processChunk_fu_92_tmp_122);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( index_reg_80 );

    SC_METHOD(thread_i_1_fu_215_p2);
    sensitive << ( stride_reg_226 );
    sensitive << ( i_reg_68 );

    SC_METHOD(thread_inSound_address0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( grp_voicerec_preprocessSound_fu_134_inSound_address0 );

    SC_METHOD(thread_inSound_ce0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( grp_voicerec_preprocessSound_fu_134_inSound_ce0 );

    SC_METHOD(thread_inSound_d0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( grp_voicerec_preprocessSound_fu_134_inSound_d0 );

    SC_METHOD(thread_inSound_we0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( grp_voicerec_preprocessSound_fu_134_inSound_we0 );

    SC_METHOD(thread_index_1_fu_209_p2);
    sensitive << ( index_reg_80 );

    SC_METHOD(thread_outSound_address0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( grp_voicerec_processChunk_fu_92_inputSound_address0 );
    sensitive << ( grp_voicerec_preprocessSound_fu_134_outSound_address0 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_outSound_ce0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( grp_voicerec_processChunk_fu_92_inputSound_ce0 );
    sensitive << ( grp_voicerec_preprocessSound_fu_134_outSound_ce0 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_outSound_d0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( grp_voicerec_preprocessSound_fu_134_outSound_d0 );

    SC_METHOD(thread_outSound_we0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( grp_voicerec_preprocessSound_fu_134_outSound_we0 );

    SC_METHOD(thread_p_lshr_f_fu_176_p4);
    sensitive << ( np );

    SC_METHOD(thread_p_lshr_fu_156_p4);
    sensitive << ( p_neg_fu_150_p2 );

    SC_METHOD(thread_p_neg_fu_150_p2);
    sensitive << ( np );

    SC_METHOD(thread_p_neg_t_fu_170_p2);
    sensitive << ( tmp_1_fu_166_p1 );

    SC_METHOD(thread_result_address0);
    sensitive << ( grp_voicerec_processChunk_fu_92_ret_address0 );
    sensitive << ( grp_voicerec_classifySound_fu_118_result_address0 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );

    SC_METHOD(thread_result_ce0);
    sensitive << ( grp_voicerec_processChunk_fu_92_ret_ce0 );
    sensitive << ( grp_voicerec_classifySound_fu_118_result_ce0 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );

    SC_METHOD(thread_result_d0);
    sensitive << ( grp_voicerec_processChunk_fu_92_ret_d0 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_result_we0);
    sensitive << ( grp_voicerec_processChunk_fu_92_ret_we0 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_stride_fu_190_p3);
    sensitive << ( tmp_3_fu_142_p3 );
    sensitive << ( p_neg_t_fu_170_p2 );
    sensitive << ( tmp_2_fu_186_p1 );

    SC_METHOD(thread_tmp_1_fu_166_p1);
    sensitive << ( p_lshr_fu_156_p4 );

    SC_METHOD(thread_tmp_2_fu_186_p1);
    sensitive << ( p_lshr_f_fu_176_p4 );

    SC_METHOD(thread_tmp_3_fu_142_p3);
    sensitive << ( np );

    SC_METHOD(thread_tmp_fu_198_p2);
    sensitive << ( np );
    sensitive << ( i_reg_68 );

    SC_METHOD(thread_tmp_s_fu_203_p2);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( tmp_fu_198_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_voicerec_preprocessSound_fu_134_ap_done );
    sensitive << ( tmp_s_fu_203_p2 );
    sensitive << ( grp_voicerec_processChunk_fu_92_ap_done );
    sensitive << ( grp_voicerec_classifySound_fu_118_ap_done );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "00001";
    grp_voicerec_processChunk_fu_92_ap_start_ap_start_reg = SC_LOGIC_0;
    grp_voicerec_classifySound_fu_118_ap_start_ap_start_reg = SC_LOGIC_0;
    grp_voicerec_preprocessSound_fu_134_ap_start_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "voicerec_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, np, "(port)np");
    sc_trace(mVcdFile, inSound_address0, "(port)inSound_address0");
    sc_trace(mVcdFile, inSound_ce0, "(port)inSound_ce0");
    sc_trace(mVcdFile, inSound_we0, "(port)inSound_we0");
    sc_trace(mVcdFile, inSound_d0, "(port)inSound_d0");
    sc_trace(mVcdFile, inSound_q0, "(port)inSound_q0");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_21, "ap_sig_bdd_21");
    sc_trace(mVcdFile, result_address0, "result_address0");
    sc_trace(mVcdFile, result_ce0, "result_ce0");
    sc_trace(mVcdFile, result_we0, "result_we0");
    sc_trace(mVcdFile, result_d0, "result_d0");
    sc_trace(mVcdFile, result_q0, "result_q0");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_55, "ap_sig_bdd_55");
    sc_trace(mVcdFile, grp_voicerec_preprocessSound_fu_134_ap_done, "grp_voicerec_preprocessSound_fu_134_ap_done");
    sc_trace(mVcdFile, stride_fu_190_p3, "stride_fu_190_p3");
    sc_trace(mVcdFile, stride_reg_226, "stride_reg_226");
    sc_trace(mVcdFile, index_1_fu_209_p2, "index_1_fu_209_p2");
    sc_trace(mVcdFile, index_1_reg_234, "index_1_reg_234");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_bdd_70, "ap_sig_bdd_70");
    sc_trace(mVcdFile, i_1_fu_215_p2, "i_1_fu_215_p2");
    sc_trace(mVcdFile, i_1_reg_239, "i_1_reg_239");
    sc_trace(mVcdFile, tmp_s_fu_203_p2, "tmp_s_fu_203_p2");
    sc_trace(mVcdFile, outSound_address0, "outSound_address0");
    sc_trace(mVcdFile, outSound_ce0, "outSound_ce0");
    sc_trace(mVcdFile, outSound_we0, "outSound_we0");
    sc_trace(mVcdFile, outSound_d0, "outSound_d0");
    sc_trace(mVcdFile, outSound_q0, "outSound_q0");
    sc_trace(mVcdFile, grp_voicerec_processChunk_fu_92_ap_start, "grp_voicerec_processChunk_fu_92_ap_start");
    sc_trace(mVcdFile, grp_voicerec_processChunk_fu_92_ap_done, "grp_voicerec_processChunk_fu_92_ap_done");
    sc_trace(mVcdFile, grp_voicerec_processChunk_fu_92_ap_idle, "grp_voicerec_processChunk_fu_92_ap_idle");
    sc_trace(mVcdFile, grp_voicerec_processChunk_fu_92_ap_ready, "grp_voicerec_processChunk_fu_92_ap_ready");
    sc_trace(mVcdFile, grp_voicerec_processChunk_fu_92_sp, "grp_voicerec_processChunk_fu_92_sp");
    sc_trace(mVcdFile, grp_voicerec_processChunk_fu_92_np, "grp_voicerec_processChunk_fu_92_np");
    sc_trace(mVcdFile, grp_voicerec_processChunk_fu_92_ret_address0, "grp_voicerec_processChunk_fu_92_ret_address0");
    sc_trace(mVcdFile, grp_voicerec_processChunk_fu_92_ret_ce0, "grp_voicerec_processChunk_fu_92_ret_ce0");
    sc_trace(mVcdFile, grp_voicerec_processChunk_fu_92_ret_we0, "grp_voicerec_processChunk_fu_92_ret_we0");
    sc_trace(mVcdFile, grp_voicerec_processChunk_fu_92_ret_d0, "grp_voicerec_processChunk_fu_92_ret_d0");
    sc_trace(mVcdFile, grp_voicerec_processChunk_fu_92_tmp_122, "grp_voicerec_processChunk_fu_92_tmp_122");
    sc_trace(mVcdFile, grp_voicerec_processChunk_fu_92_inputSound_address0, "grp_voicerec_processChunk_fu_92_inputSound_address0");
    sc_trace(mVcdFile, grp_voicerec_processChunk_fu_92_inputSound_ce0, "grp_voicerec_processChunk_fu_92_inputSound_ce0");
    sc_trace(mVcdFile, grp_voicerec_processChunk_fu_92_inputSound_q0, "grp_voicerec_processChunk_fu_92_inputSound_q0");
    sc_trace(mVcdFile, grp_voicerec_classifySound_fu_118_ap_start, "grp_voicerec_classifySound_fu_118_ap_start");
    sc_trace(mVcdFile, grp_voicerec_classifySound_fu_118_ap_done, "grp_voicerec_classifySound_fu_118_ap_done");
    sc_trace(mVcdFile, grp_voicerec_classifySound_fu_118_ap_idle, "grp_voicerec_classifySound_fu_118_ap_idle");
    sc_trace(mVcdFile, grp_voicerec_classifySound_fu_118_ap_ready, "grp_voicerec_classifySound_fu_118_ap_ready");
    sc_trace(mVcdFile, grp_voicerec_classifySound_fu_118_result_address0, "grp_voicerec_classifySound_fu_118_result_address0");
    sc_trace(mVcdFile, grp_voicerec_classifySound_fu_118_result_ce0, "grp_voicerec_classifySound_fu_118_result_ce0");
    sc_trace(mVcdFile, grp_voicerec_classifySound_fu_118_result_q0, "grp_voicerec_classifySound_fu_118_result_q0");
    sc_trace(mVcdFile, grp_voicerec_classifySound_fu_118_ap_return, "grp_voicerec_classifySound_fu_118_ap_return");
    sc_trace(mVcdFile, grp_voicerec_preprocessSound_fu_134_ap_start, "grp_voicerec_preprocessSound_fu_134_ap_start");
    sc_trace(mVcdFile, grp_voicerec_preprocessSound_fu_134_ap_idle, "grp_voicerec_preprocessSound_fu_134_ap_idle");
    sc_trace(mVcdFile, grp_voicerec_preprocessSound_fu_134_ap_ready, "grp_voicerec_preprocessSound_fu_134_ap_ready");
    sc_trace(mVcdFile, grp_voicerec_preprocessSound_fu_134_inSound_address0, "grp_voicerec_preprocessSound_fu_134_inSound_address0");
    sc_trace(mVcdFile, grp_voicerec_preprocessSound_fu_134_inSound_ce0, "grp_voicerec_preprocessSound_fu_134_inSound_ce0");
    sc_trace(mVcdFile, grp_voicerec_preprocessSound_fu_134_inSound_we0, "grp_voicerec_preprocessSound_fu_134_inSound_we0");
    sc_trace(mVcdFile, grp_voicerec_preprocessSound_fu_134_inSound_d0, "grp_voicerec_preprocessSound_fu_134_inSound_d0");
    sc_trace(mVcdFile, grp_voicerec_preprocessSound_fu_134_inSound_q0, "grp_voicerec_preprocessSound_fu_134_inSound_q0");
    sc_trace(mVcdFile, grp_voicerec_preprocessSound_fu_134_outSound_address0, "grp_voicerec_preprocessSound_fu_134_outSound_address0");
    sc_trace(mVcdFile, grp_voicerec_preprocessSound_fu_134_outSound_ce0, "grp_voicerec_preprocessSound_fu_134_outSound_ce0");
    sc_trace(mVcdFile, grp_voicerec_preprocessSound_fu_134_outSound_we0, "grp_voicerec_preprocessSound_fu_134_outSound_we0");
    sc_trace(mVcdFile, grp_voicerec_preprocessSound_fu_134_outSound_d0, "grp_voicerec_preprocessSound_fu_134_outSound_d0");
    sc_trace(mVcdFile, i_reg_68, "i_reg_68");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_3, "ap_sig_cseq_ST_st4_fsm_3");
    sc_trace(mVcdFile, ap_sig_bdd_136, "ap_sig_bdd_136");
    sc_trace(mVcdFile, index_reg_80, "index_reg_80");
    sc_trace(mVcdFile, grp_voicerec_processChunk_fu_92_ap_start_ap_start_reg, "grp_voicerec_processChunk_fu_92_ap_start_ap_start_reg");
    sc_trace(mVcdFile, grp_voicerec_classifySound_fu_118_ap_start_ap_start_reg, "grp_voicerec_classifySound_fu_118_ap_start_ap_start_reg");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st5_fsm_4, "ap_sig_cseq_ST_st5_fsm_4");
    sc_trace(mVcdFile, ap_sig_bdd_234, "ap_sig_bdd_234");
    sc_trace(mVcdFile, grp_voicerec_preprocessSound_fu_134_ap_start_ap_start_reg, "grp_voicerec_preprocessSound_fu_134_ap_start_ap_start_reg");
    sc_trace(mVcdFile, p_neg_fu_150_p2, "p_neg_fu_150_p2");
    sc_trace(mVcdFile, p_lshr_fu_156_p4, "p_lshr_fu_156_p4");
    sc_trace(mVcdFile, tmp_1_fu_166_p1, "tmp_1_fu_166_p1");
    sc_trace(mVcdFile, p_lshr_f_fu_176_p4, "p_lshr_f_fu_176_p4");
    sc_trace(mVcdFile, tmp_3_fu_142_p3, "tmp_3_fu_142_p3");
    sc_trace(mVcdFile, p_neg_t_fu_170_p2, "p_neg_t_fu_170_p2");
    sc_trace(mVcdFile, tmp_2_fu_186_p1, "tmp_2_fu_186_p1");
    sc_trace(mVcdFile, tmp_fu_198_p2, "tmp_fu_198_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("voicerec.hdltvin.dat");
    mHdltvoutHandle.open("voicerec.hdltvout.dat");
}

voicerec::~voicerec() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete result_U;
    delete outSound_U;
    delete grp_voicerec_processChunk_fu_92;
    delete grp_voicerec_classifySound_fu_118;
    delete grp_voicerec_preprocessSound_fu_134;
}

void voicerec::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_voicerec_classifySound_fu_118_ap_start_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
             esl_seteq<1,1,1>(tmp_s_fu_203_p2.read(), ap_const_lv1_0))) {
            grp_voicerec_classifySound_fu_118_ap_start_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_voicerec_classifySound_fu_118_ap_ready.read())) {
            grp_voicerec_classifySound_fu_118_ap_start_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_voicerec_preprocessSound_fu_134_ap_start_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
             !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            grp_voicerec_preprocessSound_fu_134_ap_start_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_voicerec_preprocessSound_fu_134_ap_ready.read())) {
            grp_voicerec_preprocessSound_fu_134_ap_start_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_voicerec_processChunk_fu_92_ap_start_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
             !esl_seteq<1,1,1>(tmp_s_fu_203_p2.read(), ap_const_lv1_0))) {
            grp_voicerec_processChunk_fu_92_ap_start_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_voicerec_processChunk_fu_92_ap_ready.read())) {
            grp_voicerec_processChunk_fu_92_ap_start_ap_start_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
         !esl_seteq<1,1,1>(ap_const_logic_0, grp_voicerec_processChunk_fu_92_ap_done.read()))) {
        i_reg_68 = i_1_reg_239.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                !esl_seteq<1,1,1>(ap_const_logic_0, grp_voicerec_preprocessSound_fu_134_ap_done.read()))) {
        i_reg_68 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
         !esl_seteq<1,1,1>(ap_const_logic_0, grp_voicerec_processChunk_fu_92_ap_done.read()))) {
        index_reg_80 = index_1_reg_234.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                !esl_seteq<1,1,1>(ap_const_logic_0, grp_voicerec_preprocessSound_fu_134_ap_done.read()))) {
        index_reg_80 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && !esl_seteq<1,1,1>(tmp_s_fu_203_p2.read(), ap_const_lv1_0))) {
        i_1_reg_239 = i_1_fu_215_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        index_1_reg_234 = index_1_fu_209_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && !esl_seteq<1,1,1>(ap_const_logic_0, grp_voicerec_preprocessSound_fu_134_ap_done.read()))) {
        stride_reg_226 = stride_fu_190_p3.read();
    }
}

void voicerec::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && 
         !esl_seteq<1,1,1>(ap_const_logic_0, grp_voicerec_classifySound_fu_118_ap_done.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void voicerec::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void voicerec::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && 
         !esl_seteq<1,1,1>(ap_const_logic_0, grp_voicerec_classifySound_fu_118_ap_done.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void voicerec::thread_ap_return() {
    ap_return = grp_voicerec_classifySound_fu_118_ap_return.read();
}

void voicerec::thread_ap_sig_bdd_136() {
    ap_sig_bdd_136 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void voicerec::thread_ap_sig_bdd_21() {
    ap_sig_bdd_21 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void voicerec::thread_ap_sig_bdd_234() {
    ap_sig_bdd_234 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(4, 4));
}

void voicerec::thread_ap_sig_bdd_55() {
    ap_sig_bdd_55 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void voicerec::thread_ap_sig_bdd_70() {
    ap_sig_bdd_70 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void voicerec::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_21.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void voicerec::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_bdd_55.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void voicerec::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_bdd_70.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void voicerec::thread_ap_sig_cseq_ST_st4_fsm_3() {
    if (ap_sig_bdd_136.read()) {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    }
}

void voicerec::thread_ap_sig_cseq_ST_st5_fsm_4() {
    if (ap_sig_bdd_234.read()) {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    }
}

void voicerec::thread_grp_voicerec_classifySound_fu_118_ap_start() {
    grp_voicerec_classifySound_fu_118_ap_start = grp_voicerec_classifySound_fu_118_ap_start_ap_start_reg.read();
}

void voicerec::thread_grp_voicerec_classifySound_fu_118_result_q0() {
    grp_voicerec_classifySound_fu_118_result_q0 = result_q0.read();
}

void voicerec::thread_grp_voicerec_preprocessSound_fu_134_ap_start() {
    grp_voicerec_preprocessSound_fu_134_ap_start = grp_voicerec_preprocessSound_fu_134_ap_start_ap_start_reg.read();
}

void voicerec::thread_grp_voicerec_preprocessSound_fu_134_inSound_q0() {
    grp_voicerec_preprocessSound_fu_134_inSound_q0 = inSound_q0.read();
}

void voicerec::thread_grp_voicerec_processChunk_fu_92_ap_start() {
    grp_voicerec_processChunk_fu_92_ap_start = grp_voicerec_processChunk_fu_92_ap_start_ap_start_reg.read();
}

void voicerec::thread_grp_voicerec_processChunk_fu_92_inputSound_q0() {
    grp_voicerec_processChunk_fu_92_inputSound_q0 = outSound_q0.read();
}

void voicerec::thread_grp_voicerec_processChunk_fu_92_np() {
    grp_voicerec_processChunk_fu_92_np = np.read();
}

void voicerec::thread_grp_voicerec_processChunk_fu_92_sp() {
    grp_voicerec_processChunk_fu_92_sp = i_reg_68.read();
}

void voicerec::thread_grp_voicerec_processChunk_fu_92_tmp_122() {
    grp_voicerec_processChunk_fu_92_tmp_122 = index_reg_80.read();
}

void voicerec::thread_i_1_fu_215_p2() {
    i_1_fu_215_p2 = (!stride_reg_226.read().is_01() || !i_reg_68.read().is_01())? sc_lv<32>(): (sc_biguint<32>(stride_reg_226.read()) + sc_biguint<32>(i_reg_68.read()));
}

void voicerec::thread_inSound_address0() {
    inSound_address0 = grp_voicerec_preprocessSound_fu_134_inSound_address0.read();
}

void voicerec::thread_inSound_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        inSound_ce0 = grp_voicerec_preprocessSound_fu_134_inSound_ce0.read();
    } else {
        inSound_ce0 = ap_const_logic_0;
    }
}

void voicerec::thread_inSound_d0() {
    inSound_d0 = grp_voicerec_preprocessSound_fu_134_inSound_d0.read();
}

void voicerec::thread_inSound_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        inSound_we0 = grp_voicerec_preprocessSound_fu_134_inSound_we0.read();
    } else {
        inSound_we0 = ap_const_logic_0;
    }
}

void voicerec::thread_index_1_fu_209_p2() {
    index_1_fu_209_p2 = (!index_reg_80.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(index_reg_80.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void voicerec::thread_outSound_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        outSound_address0 = grp_voicerec_preprocessSound_fu_134_outSound_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        outSound_address0 = grp_voicerec_processChunk_fu_92_inputSound_address0.read();
    } else {
        outSound_address0 = "XXXXXXXXXXXXX";
    }
}

void voicerec::thread_outSound_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        outSound_ce0 = grp_voicerec_preprocessSound_fu_134_outSound_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        outSound_ce0 = grp_voicerec_processChunk_fu_92_inputSound_ce0.read();
    } else {
        outSound_ce0 = ap_const_logic_0;
    }
}

void voicerec::thread_outSound_d0() {
    outSound_d0 = grp_voicerec_preprocessSound_fu_134_outSound_d0.read();
}

void voicerec::thread_outSound_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        outSound_we0 = grp_voicerec_preprocessSound_fu_134_outSound_we0.read();
    } else {
        outSound_we0 = ap_const_logic_0;
    }
}

void voicerec::thread_p_lshr_f_fu_176_p4() {
    p_lshr_f_fu_176_p4 = np.read().range(31, 1);
}

void voicerec::thread_p_lshr_fu_156_p4() {
    p_lshr_fu_156_p4 = p_neg_fu_150_p2.read().range(31, 1);
}

void voicerec::thread_p_neg_fu_150_p2() {
    p_neg_fu_150_p2 = (!ap_const_lv32_0.is_01() || !np.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_0) - sc_biguint<32>(np.read()));
}

void voicerec::thread_p_neg_t_fu_170_p2() {
    p_neg_t_fu_170_p2 = (!ap_const_lv32_0.is_01() || !tmp_1_fu_166_p1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_0) - sc_biguint<32>(tmp_1_fu_166_p1.read()));
}

void voicerec::thread_result_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        result_address0 = grp_voicerec_classifySound_fu_118_result_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        result_address0 = grp_voicerec_processChunk_fu_92_ret_address0.read();
    } else {
        result_address0 =  (sc_lv<10>) ("XXXXXXXXXX");
    }
}

void voicerec::thread_result_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        result_ce0 = grp_voicerec_classifySound_fu_118_result_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        result_ce0 = grp_voicerec_processChunk_fu_92_ret_ce0.read();
    } else {
        result_ce0 = ap_const_logic_0;
    }
}

void voicerec::thread_result_d0() {
    result_d0 = grp_voicerec_processChunk_fu_92_ret_d0.read();
}

void voicerec::thread_result_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        result_we0 = grp_voicerec_processChunk_fu_92_ret_we0.read();
    } else {
        result_we0 = ap_const_logic_0;
    }
}

void voicerec::thread_stride_fu_190_p3() {
    stride_fu_190_p3 = (!tmp_3_fu_142_p3.read()[0].is_01())? sc_lv<32>(): ((tmp_3_fu_142_p3.read()[0].to_bool())? p_neg_t_fu_170_p2.read(): tmp_2_fu_186_p1.read());
}

void voicerec::thread_tmp_1_fu_166_p1() {
    tmp_1_fu_166_p1 = esl_zext<32,31>(p_lshr_fu_156_p4.read());
}

void voicerec::thread_tmp_2_fu_186_p1() {
    tmp_2_fu_186_p1 = esl_zext<32,31>(p_lshr_f_fu_176_p4.read());
}

void voicerec::thread_tmp_3_fu_142_p3() {
    tmp_3_fu_142_p3 = np.read().range(31, 31);
}

void voicerec::thread_tmp_fu_198_p2() {
    tmp_fu_198_p2 = (!i_reg_68.read().is_01() || !np.read().is_01())? sc_lv<32>(): (sc_biguint<32>(i_reg_68.read()) + sc_biguint<32>(np.read()));
}

void voicerec::thread_tmp_s_fu_203_p2() {
    tmp_s_fu_203_p2 = (!tmp_fu_198_p2.read().is_01() || !ap_const_lv32_1F40.is_01())? sc_lv<1>(): (sc_bigint<32>(tmp_fu_198_p2.read()) < sc_bigint<32>(ap_const_lv32_1F40));
}

void voicerec::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_0, grp_voicerec_preprocessSound_fu_134_ap_done.read())) {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            } else {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            }
            break;
        case 4 : 
            if (esl_seteq<1,1,1>(tmp_s_fu_203_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st5_fsm_4;
            } else {
                ap_NS_fsm = ap_ST_st4_fsm_3;
            }
            break;
        case 8 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_0, grp_voicerec_processChunk_fu_92_ap_done.read())) {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            } else {
                ap_NS_fsm = ap_ST_st4_fsm_3;
            }
            break;
        case 16 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_0, grp_voicerec_classifySound_fu_118_ap_done.read())) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st5_fsm_4;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<5>) ("XXXXX");
            break;
    }
}

void voicerec::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"np\" :  \"" << np.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"inSound_address0\" :  \"" << inSound_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"inSound_ce0\" :  \"" << inSound_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"inSound_we0\" :  \"" << inSound_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"inSound_d0\" :  \"" << inSound_d0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inSound_q0\" :  \"" << inSound_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_return\" :  \"" << ap_return.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

