// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "voicerec_classifySound.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic voicerec_classifySound::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic voicerec_classifySound::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<9> voicerec_classifySound::ap_ST_st1_fsm_0 = "1";
const sc_lv<9> voicerec_classifySound::ap_ST_st2_fsm_1 = "10";
const sc_lv<9> voicerec_classifySound::ap_ST_st3_fsm_2 = "100";
const sc_lv<9> voicerec_classifySound::ap_ST_st4_fsm_3 = "1000";
const sc_lv<9> voicerec_classifySound::ap_ST_st5_fsm_4 = "10000";
const sc_lv<9> voicerec_classifySound::ap_ST_st6_fsm_5 = "100000";
const sc_lv<9> voicerec_classifySound::ap_ST_st7_fsm_6 = "1000000";
const sc_lv<9> voicerec_classifySound::ap_ST_st8_fsm_7 = "10000000";
const sc_lv<9> voicerec_classifySound::ap_ST_st9_fsm_8 = "100000000";
const sc_lv<32> voicerec_classifySound::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> voicerec_classifySound::ap_const_lv1_1 = "1";
const sc_lv<32> voicerec_classifySound::ap_const_lv32_1 = "1";
const sc_lv<1> voicerec_classifySound::ap_const_lv1_0 = "0";
const sc_lv<32> voicerec_classifySound::ap_const_lv32_2 = "10";
const sc_lv<32> voicerec_classifySound::ap_const_lv32_5 = "101";
const sc_lv<32> voicerec_classifySound::ap_const_lv32_6 = "110";
const sc_lv<32> voicerec_classifySound::ap_const_lv32_7 = "111";
const sc_lv<32> voicerec_classifySound::ap_const_lv32_8 = "1000";
const sc_lv<6> voicerec_classifySound::ap_const_lv6_0 = "000000";
const sc_lv<32> voicerec_classifySound::ap_const_lv32_3 = "11";
const sc_lv<4> voicerec_classifySound::ap_const_lv4_0 = "0000";
const sc_lv<3> voicerec_classifySound::ap_const_lv3_0 = "000";
const sc_lv<32> voicerec_classifySound::ap_const_lv32_4 = "100";
const sc_lv<6> voicerec_classifySound::ap_const_lv6_3F = "111111";
const sc_lv<6> voicerec_classifySound::ap_const_lv6_1 = "1";
const sc_lv<4> voicerec_classifySound::ap_const_lv4_E = "1110";
const sc_lv<4> voicerec_classifySound::ap_const_lv4_1 = "1";
const sc_lv<3> voicerec_classifySound::ap_const_lv3_4 = "100";
const sc_lv<3> voicerec_classifySound::ap_const_lv3_1 = "1";
const sc_lv<32> voicerec_classifySound::ap_const_lv32_17 = "10111";
const sc_lv<32> voicerec_classifySound::ap_const_lv32_1E = "11110";
const sc_lv<8> voicerec_classifySound::ap_const_lv8_FF = "11111111";
const sc_lv<23> voicerec_classifySound::ap_const_lv23_0 = "00000000000000000000000";
const sc_lv<5> voicerec_classifySound::ap_const_lv5_2 = "10";

voicerec_classifySound::voicerec_classifySound(sc_module_name name) : sc_module(name), mVcdFile(0) {
    output_r_U = new voicerec_classifySound_output_r("output_r_U");
    output_r_U->clk(ap_clk);
    output_r_U->reset(ap_rst);
    output_r_U->address0(output_r_address0);
    output_r_U->ce0(output_r_ce0);
    output_r_U->we0(output_r_we0);
    output_r_U->d0(output_r_d0);
    output_r_U->q0(output_r_q0);
    flatInput_U = new voicerec_classifySound_flatInput("flatInput_U");
    flatInput_U->clk(ap_clk);
    flatInput_U->reset(ap_rst);
    flatInput_U->address0(flatInput_address0);
    flatInput_U->ce0(flatInput_ce0);
    flatInput_U->we0(flatInput_we0);
    flatInput_U->d0(flatInput_d0);
    flatInput_U->q0(flatInput_q0);
    grp_voicerec_feedForward_fu_161 = new voicerec_feedForward("grp_voicerec_feedForward_fu_161");
    grp_voicerec_feedForward_fu_161->ap_clk(ap_clk);
    grp_voicerec_feedForward_fu_161->ap_rst(ap_rst);
    grp_voicerec_feedForward_fu_161->ap_start(grp_voicerec_feedForward_fu_161_ap_start);
    grp_voicerec_feedForward_fu_161->ap_done(grp_voicerec_feedForward_fu_161_ap_done);
    grp_voicerec_feedForward_fu_161->ap_idle(grp_voicerec_feedForward_fu_161_ap_idle);
    grp_voicerec_feedForward_fu_161->ap_ready(grp_voicerec_feedForward_fu_161_ap_ready);
    grp_voicerec_feedForward_fu_161->pattern_address0(grp_voicerec_feedForward_fu_161_pattern_address0);
    grp_voicerec_feedForward_fu_161->pattern_ce0(grp_voicerec_feedForward_fu_161_pattern_ce0);
    grp_voicerec_feedForward_fu_161->pattern_q0(grp_voicerec_feedForward_fu_161_pattern_q0);
    grp_voicerec_feedForward_fu_161->output_r_address0(grp_voicerec_feedForward_fu_161_output_r_address0);
    grp_voicerec_feedForward_fu_161->output_r_ce0(grp_voicerec_feedForward_fu_161_output_r_ce0);
    grp_voicerec_feedForward_fu_161->output_r_we0(grp_voicerec_feedForward_fu_161_output_r_we0);
    grp_voicerec_feedForward_fu_161->output_r_d0(grp_voicerec_feedForward_fu_161_output_r_d0);
    voicerec_fcmp_32ns_32ns_1_1_U46 = new voicerec_fcmp_32ns_32ns_1_1<1,1,32,32,1>("voicerec_fcmp_32ns_32ns_1_1_U46");
    voicerec_fcmp_32ns_32ns_1_1_U46->din0(tmp_6_fu_176_p0);
    voicerec_fcmp_32ns_32ns_1_1_U46->din1(tmp_6_fu_176_p1);
    voicerec_fcmp_32ns_32ns_1_1_U46->opcode(tmp_6_fu_176_opcode);
    voicerec_fcmp_32ns_32ns_1_1_U46->dout(tmp_6_fu_176_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( exitcond_i_fu_278_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( exitcond_i_fu_278_p2 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( exitcond_i_fu_278_p2 );
    sensitive << ( guess_i_reg_137 );
    sensitive << ( ap_return_preg );

    SC_METHOD(thread_ap_sig_bdd_104);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_113);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_122);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_164);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_175);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_27);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_56);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_73);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_89);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_27 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_bdd_56 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_bdd_73 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_3);
    sensitive << ( ap_sig_bdd_164 );

    SC_METHOD(thread_ap_sig_cseq_ST_st5_fsm_4);
    sensitive << ( ap_sig_bdd_175 );

    SC_METHOD(thread_ap_sig_cseq_ST_st6_fsm_5);
    sensitive << ( ap_sig_bdd_89 );

    SC_METHOD(thread_ap_sig_cseq_ST_st7_fsm_6);
    sensitive << ( ap_sig_bdd_104 );

    SC_METHOD(thread_ap_sig_cseq_ST_st8_fsm_7);
    sensitive << ( ap_sig_bdd_113 );

    SC_METHOD(thread_ap_sig_cseq_ST_st9_fsm_8);
    sensitive << ( ap_sig_bdd_122 );

    SC_METHOD(thread_exitcond1_fu_181_p2);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( i_reg_104 );

    SC_METHOD(thread_exitcond_fu_231_p2);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( j_reg_115 );

    SC_METHOD(thread_exitcond_i_fu_278_p2);
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( guess_reg_126 );

    SC_METHOD(thread_flatInput_address0);
    sensitive << ( grp_voicerec_feedForward_fu_161_pattern_address0 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( tmp_3_fu_269_p1 );

    SC_METHOD(thread_flatInput_ce0);
    sensitive << ( grp_voicerec_feedForward_fu_161_pattern_ce0 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );

    SC_METHOD(thread_flatInput_d0);
    sensitive << ( result_q0 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_flatInput_we0);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_grp_voicerec_feedForward_fu_161_ap_start);
    sensitive << ( grp_voicerec_feedForward_fu_161_ap_start_ap_start_reg );

    SC_METHOD(thread_grp_voicerec_feedForward_fu_161_pattern_q0);
    sensitive << ( flatInput_q0 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );

    SC_METHOD(thread_guess_1_fu_377_p3);
    sensitive << ( guess_cast1_reg_427 );
    sensitive << ( guess_i_reg_137 );
    sensitive << ( tmp_10_fu_372_p2 );

    SC_METHOD(thread_guess_cast1_fu_274_p1);
    sensitive << ( guess_reg_126 );

    SC_METHOD(thread_i_1_fu_187_p2);
    sensitive << ( i_reg_104 );

    SC_METHOD(thread_j_1_fu_237_p2);
    sensitive << ( j_reg_115 );

    SC_METHOD(thread_j_2_fu_284_p2);
    sensitive << ( guess_reg_126 );

    SC_METHOD(thread_j_cast3_fu_227_p1);
    sensitive << ( j_reg_115 );

    SC_METHOD(thread_max_1_fu_384_p3);
    sensitive << ( max_reg_445 );
    sensitive << ( second_max_reg_149 );
    sensitive << ( tmp_10_fu_372_p2 );

    SC_METHOD(thread_max_to_int_fu_295_p1);
    sensitive << ( max_reg_445 );

    SC_METHOD(thread_notlhs6_fu_348_p2);
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( tmp_5_fu_316_p4 );

    SC_METHOD(thread_notlhs_fu_330_p2);
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( tmp_fu_298_p4 );

    SC_METHOD(thread_notrhs7_fu_354_p2);
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( tmp_4_fu_326_p1 );

    SC_METHOD(thread_notrhs_fu_336_p2);
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( tmp_1_fu_308_p1 );

    SC_METHOD(thread_output_r_address0);
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( grp_voicerec_feedForward_fu_161_output_r_address0 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( tmp_i_fu_290_p1 );

    SC_METHOD(thread_output_r_ce0);
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( grp_voicerec_feedForward_fu_161_output_r_ce0 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );

    SC_METHOD(thread_output_r_d0);
    sensitive << ( grp_voicerec_feedForward_fu_161_output_r_d0 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );

    SC_METHOD(thread_output_r_we0);
    sensitive << ( grp_voicerec_feedForward_fu_161_output_r_we0 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );

    SC_METHOD(thread_p_shl2_cast_fu_213_p1);
    sensitive << ( p_shl2_fu_205_p3 );

    SC_METHOD(thread_p_shl2_fu_205_p3);
    sensitive << ( i_reg_104 );

    SC_METHOD(thread_p_shl_cast_fu_201_p1);
    sensitive << ( p_shl_fu_193_p3 );

    SC_METHOD(thread_p_shl_fu_193_p3);
    sensitive << ( i_reg_104 );

    SC_METHOD(thread_result_addr1_cast_fu_223_p1);
    sensitive << ( tmp_9_fu_217_p2 );

    SC_METHOD(thread_result_addr2_cast_fu_252_p1);
    sensitive << ( result_addr2_fu_247_p2 );

    SC_METHOD(thread_result_addr2_fu_247_p2);
    sensitive << ( result_addr1_cast_reg_404 );
    sensitive << ( tmp_1_trn_cast_fu_243_p1 );

    SC_METHOD(thread_result_address0);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( tmp_11_fu_256_p1 );

    SC_METHOD(thread_result_ce0);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_second_max_to_int_fu_312_p1);
    sensitive << ( second_max_reg_149 );

    SC_METHOD(thread_tmp_10_fu_372_p2);
    sensitive << ( tmp_6_reg_452 );
    sensitive << ( tmp_s_fu_366_p2 );

    SC_METHOD(thread_tmp_11_fu_256_p1);
    sensitive << ( result_addr2_cast_fu_252_p1 );

    SC_METHOD(thread_tmp_1_fu_308_p1);
    sensitive << ( max_to_int_fu_295_p1 );

    SC_METHOD(thread_tmp_1_trn_cast_fu_243_p1);
    sensitive << ( j_reg_115 );

    SC_METHOD(thread_tmp_2_cast_fu_266_p1);
    sensitive << ( tmp_2_reg_422 );

    SC_METHOD(thread_tmp_2_fu_261_p2);
    sensitive << ( tmp_9_reg_399 );
    sensitive << ( j_cast3_fu_227_p1 );

    SC_METHOD(thread_tmp_3_fu_269_p1);
    sensitive << ( tmp_2_cast_fu_266_p1 );

    SC_METHOD(thread_tmp_4_fu_326_p1);
    sensitive << ( second_max_to_int_fu_312_p1 );

    SC_METHOD(thread_tmp_5_fu_316_p4);
    sensitive << ( second_max_to_int_fu_312_p1 );

    SC_METHOD(thread_tmp_6_fu_176_opcode);
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );

    SC_METHOD(thread_tmp_6_fu_176_p0);
    sensitive << ( max_reg_445 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );

    SC_METHOD(thread_tmp_6_fu_176_p1);
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( second_max_reg_149 );

    SC_METHOD(thread_tmp_7_fu_342_p2);
    sensitive << ( notrhs_fu_336_p2 );
    sensitive << ( notlhs_fu_330_p2 );

    SC_METHOD(thread_tmp_8_fu_360_p2);
    sensitive << ( notrhs7_fu_354_p2 );
    sensitive << ( notlhs6_fu_348_p2 );

    SC_METHOD(thread_tmp_9_fu_217_p2);
    sensitive << ( p_shl_cast_fu_201_p1 );
    sensitive << ( p_shl2_cast_fu_213_p1 );

    SC_METHOD(thread_tmp_fu_298_p4);
    sensitive << ( max_to_int_fu_295_p1 );

    SC_METHOD(thread_tmp_i_fu_290_p1);
    sensitive << ( guess_reg_126 );

    SC_METHOD(thread_tmp_s_fu_366_p2);
    sensitive << ( tmp_7_fu_342_p2 );
    sensitive << ( tmp_8_fu_360_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond1_fu_181_p2 );
    sensitive << ( exitcond_fu_231_p2 );
    sensitive << ( exitcond_i_fu_278_p2 );
    sensitive << ( grp_voicerec_feedForward_fu_161_ap_done );

    ap_CS_fsm = "000000001";
    grp_voicerec_feedForward_fu_161_ap_start_ap_start_reg = SC_LOGIC_0;
    ap_return_preg = "00000000000000000000000000000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "voicerec_classifySound_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, result_address0, "(port)result_address0");
    sc_trace(mVcdFile, result_ce0, "(port)result_ce0");
    sc_trace(mVcdFile, result_q0, "(port)result_q0");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_27, "ap_sig_bdd_27");
    sc_trace(mVcdFile, output_r_address0, "output_r_address0");
    sc_trace(mVcdFile, output_r_ce0, "output_r_ce0");
    sc_trace(mVcdFile, output_r_we0, "output_r_we0");
    sc_trace(mVcdFile, output_r_d0, "output_r_d0");
    sc_trace(mVcdFile, output_r_q0, "output_r_q0");
    sc_trace(mVcdFile, i_1_fu_187_p2, "i_1_fu_187_p2");
    sc_trace(mVcdFile, i_1_reg_394, "i_1_reg_394");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_56, "ap_sig_bdd_56");
    sc_trace(mVcdFile, tmp_9_fu_217_p2, "tmp_9_fu_217_p2");
    sc_trace(mVcdFile, tmp_9_reg_399, "tmp_9_reg_399");
    sc_trace(mVcdFile, exitcond1_fu_181_p2, "exitcond1_fu_181_p2");
    sc_trace(mVcdFile, result_addr1_cast_fu_223_p1, "result_addr1_cast_fu_223_p1");
    sc_trace(mVcdFile, result_addr1_cast_reg_404, "result_addr1_cast_reg_404");
    sc_trace(mVcdFile, j_1_fu_237_p2, "j_1_fu_237_p2");
    sc_trace(mVcdFile, j_1_reg_412, "j_1_reg_412");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_bdd_73, "ap_sig_bdd_73");
    sc_trace(mVcdFile, exitcond_fu_231_p2, "exitcond_fu_231_p2");
    sc_trace(mVcdFile, tmp_2_fu_261_p2, "tmp_2_fu_261_p2");
    sc_trace(mVcdFile, tmp_2_reg_422, "tmp_2_reg_422");
    sc_trace(mVcdFile, guess_cast1_fu_274_p1, "guess_cast1_fu_274_p1");
    sc_trace(mVcdFile, guess_cast1_reg_427, "guess_cast1_reg_427");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st6_fsm_5, "ap_sig_cseq_ST_st6_fsm_5");
    sc_trace(mVcdFile, ap_sig_bdd_89, "ap_sig_bdd_89");
    sc_trace(mVcdFile, j_2_fu_284_p2, "j_2_fu_284_p2");
    sc_trace(mVcdFile, j_2_reg_435, "j_2_reg_435");
    sc_trace(mVcdFile, exitcond_i_fu_278_p2, "exitcond_i_fu_278_p2");
    sc_trace(mVcdFile, max_reg_445, "max_reg_445");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st7_fsm_6, "ap_sig_cseq_ST_st7_fsm_6");
    sc_trace(mVcdFile, ap_sig_bdd_104, "ap_sig_bdd_104");
    sc_trace(mVcdFile, tmp_6_fu_176_p2, "tmp_6_fu_176_p2");
    sc_trace(mVcdFile, tmp_6_reg_452, "tmp_6_reg_452");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st8_fsm_7, "ap_sig_cseq_ST_st8_fsm_7");
    sc_trace(mVcdFile, ap_sig_bdd_113, "ap_sig_bdd_113");
    sc_trace(mVcdFile, guess_1_fu_377_p3, "guess_1_fu_377_p3");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st9_fsm_8, "ap_sig_cseq_ST_st9_fsm_8");
    sc_trace(mVcdFile, ap_sig_bdd_122, "ap_sig_bdd_122");
    sc_trace(mVcdFile, max_1_fu_384_p3, "max_1_fu_384_p3");
    sc_trace(mVcdFile, flatInput_address0, "flatInput_address0");
    sc_trace(mVcdFile, flatInput_ce0, "flatInput_ce0");
    sc_trace(mVcdFile, flatInput_we0, "flatInput_we0");
    sc_trace(mVcdFile, flatInput_d0, "flatInput_d0");
    sc_trace(mVcdFile, flatInput_q0, "flatInput_q0");
    sc_trace(mVcdFile, grp_voicerec_feedForward_fu_161_ap_start, "grp_voicerec_feedForward_fu_161_ap_start");
    sc_trace(mVcdFile, grp_voicerec_feedForward_fu_161_ap_done, "grp_voicerec_feedForward_fu_161_ap_done");
    sc_trace(mVcdFile, grp_voicerec_feedForward_fu_161_ap_idle, "grp_voicerec_feedForward_fu_161_ap_idle");
    sc_trace(mVcdFile, grp_voicerec_feedForward_fu_161_ap_ready, "grp_voicerec_feedForward_fu_161_ap_ready");
    sc_trace(mVcdFile, grp_voicerec_feedForward_fu_161_pattern_address0, "grp_voicerec_feedForward_fu_161_pattern_address0");
    sc_trace(mVcdFile, grp_voicerec_feedForward_fu_161_pattern_ce0, "grp_voicerec_feedForward_fu_161_pattern_ce0");
    sc_trace(mVcdFile, grp_voicerec_feedForward_fu_161_pattern_q0, "grp_voicerec_feedForward_fu_161_pattern_q0");
    sc_trace(mVcdFile, grp_voicerec_feedForward_fu_161_output_r_address0, "grp_voicerec_feedForward_fu_161_output_r_address0");
    sc_trace(mVcdFile, grp_voicerec_feedForward_fu_161_output_r_ce0, "grp_voicerec_feedForward_fu_161_output_r_ce0");
    sc_trace(mVcdFile, grp_voicerec_feedForward_fu_161_output_r_we0, "grp_voicerec_feedForward_fu_161_output_r_we0");
    sc_trace(mVcdFile, grp_voicerec_feedForward_fu_161_output_r_d0, "grp_voicerec_feedForward_fu_161_output_r_d0");
    sc_trace(mVcdFile, i_reg_104, "i_reg_104");
    sc_trace(mVcdFile, j_reg_115, "j_reg_115");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_3, "ap_sig_cseq_ST_st4_fsm_3");
    sc_trace(mVcdFile, ap_sig_bdd_164, "ap_sig_bdd_164");
    sc_trace(mVcdFile, guess_reg_126, "guess_reg_126");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st5_fsm_4, "ap_sig_cseq_ST_st5_fsm_4");
    sc_trace(mVcdFile, ap_sig_bdd_175, "ap_sig_bdd_175");
    sc_trace(mVcdFile, guess_i_reg_137, "guess_i_reg_137");
    sc_trace(mVcdFile, second_max_reg_149, "second_max_reg_149");
    sc_trace(mVcdFile, grp_voicerec_feedForward_fu_161_ap_start_ap_start_reg, "grp_voicerec_feedForward_fu_161_ap_start_ap_start_reg");
    sc_trace(mVcdFile, tmp_11_fu_256_p1, "tmp_11_fu_256_p1");
    sc_trace(mVcdFile, tmp_3_fu_269_p1, "tmp_3_fu_269_p1");
    sc_trace(mVcdFile, tmp_i_fu_290_p1, "tmp_i_fu_290_p1");
    sc_trace(mVcdFile, tmp_6_fu_176_p0, "tmp_6_fu_176_p0");
    sc_trace(mVcdFile, tmp_6_fu_176_p1, "tmp_6_fu_176_p1");
    sc_trace(mVcdFile, p_shl_fu_193_p3, "p_shl_fu_193_p3");
    sc_trace(mVcdFile, p_shl2_fu_205_p3, "p_shl2_fu_205_p3");
    sc_trace(mVcdFile, p_shl_cast_fu_201_p1, "p_shl_cast_fu_201_p1");
    sc_trace(mVcdFile, p_shl2_cast_fu_213_p1, "p_shl2_cast_fu_213_p1");
    sc_trace(mVcdFile, tmp_1_trn_cast_fu_243_p1, "tmp_1_trn_cast_fu_243_p1");
    sc_trace(mVcdFile, result_addr2_fu_247_p2, "result_addr2_fu_247_p2");
    sc_trace(mVcdFile, result_addr2_cast_fu_252_p1, "result_addr2_cast_fu_252_p1");
    sc_trace(mVcdFile, j_cast3_fu_227_p1, "j_cast3_fu_227_p1");
    sc_trace(mVcdFile, tmp_2_cast_fu_266_p1, "tmp_2_cast_fu_266_p1");
    sc_trace(mVcdFile, max_to_int_fu_295_p1, "max_to_int_fu_295_p1");
    sc_trace(mVcdFile, second_max_to_int_fu_312_p1, "second_max_to_int_fu_312_p1");
    sc_trace(mVcdFile, tmp_fu_298_p4, "tmp_fu_298_p4");
    sc_trace(mVcdFile, tmp_1_fu_308_p1, "tmp_1_fu_308_p1");
    sc_trace(mVcdFile, notrhs_fu_336_p2, "notrhs_fu_336_p2");
    sc_trace(mVcdFile, notlhs_fu_330_p2, "notlhs_fu_330_p2");
    sc_trace(mVcdFile, tmp_5_fu_316_p4, "tmp_5_fu_316_p4");
    sc_trace(mVcdFile, tmp_4_fu_326_p1, "tmp_4_fu_326_p1");
    sc_trace(mVcdFile, notrhs7_fu_354_p2, "notrhs7_fu_354_p2");
    sc_trace(mVcdFile, notlhs6_fu_348_p2, "notlhs6_fu_348_p2");
    sc_trace(mVcdFile, tmp_7_fu_342_p2, "tmp_7_fu_342_p2");
    sc_trace(mVcdFile, tmp_8_fu_360_p2, "tmp_8_fu_360_p2");
    sc_trace(mVcdFile, tmp_s_fu_366_p2, "tmp_s_fu_366_p2");
    sc_trace(mVcdFile, tmp_10_fu_372_p2, "tmp_10_fu_372_p2");
    sc_trace(mVcdFile, tmp_6_fu_176_opcode, "tmp_6_fu_176_opcode");
    sc_trace(mVcdFile, ap_return_preg, "ap_return_preg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

voicerec_classifySound::~voicerec_classifySound() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete output_r_U;
    delete flatInput_U;
    delete grp_voicerec_feedForward_fu_161;
    delete voicerec_fcmp_32ns_32ns_1_1_U46;
}

void voicerec_classifySound::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_preg = ap_const_lv32_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && 
             !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_fu_278_p2.read()))) {
            ap_return_preg = guess_i_reg_137.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_voicerec_feedForward_fu_161_ap_start_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
             !esl_seteq<1,1,1>(exitcond1_fu_181_p2.read(), ap_const_lv1_0))) {
            grp_voicerec_feedForward_fu_161_ap_start_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_voicerec_feedForward_fu_161_ap_ready.read())) {
            grp_voicerec_feedForward_fu_161_ap_start_ap_start_reg = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
        guess_reg_126 = j_2_reg_435.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && 
                !esl_seteq<1,1,1>(ap_const_logic_0, grp_voicerec_feedForward_fu_161_ap_done.read()))) {
        guess_reg_126 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_231_p2.read()))) {
        i_reg_104 = i_1_reg_394.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        i_reg_104 = ap_const_lv6_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond1_fu_181_p2.read(), ap_const_lv1_0))) {
        j_reg_115 = ap_const_lv4_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        j_reg_115 = j_1_reg_412.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
        second_max_reg_149 = max_1_fu_384_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && 
                !esl_seteq<1,1,1>(ap_const_logic_0, grp_voicerec_feedForward_fu_161_ap_done.read()))) {
        second_max_reg_149 = ap_const_lv32_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        guess_cast1_reg_427 = guess_cast1_fu_274_p1.read();
        j_2_reg_435 = j_2_fu_284_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
        guess_i_reg_137 = guess_1_fu_377_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        i_1_reg_394 = i_1_fu_187_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        j_1_reg_412 = j_1_fu_237_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        max_reg_445 = output_r_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && esl_seteq<1,1,1>(exitcond1_fu_181_p2.read(), ap_const_lv1_0))) {
        result_addr1_cast_reg_404 = result_addr1_cast_fu_223_p1.read();
        tmp_9_reg_399 = tmp_9_fu_217_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_231_p2.read()))) {
        tmp_2_reg_422 = tmp_2_fu_261_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        tmp_6_reg_452 = tmp_6_fu_176_p2.read();
    }
}

void voicerec_classifySound::thread_ap_done() {
    if (((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_fu_278_p2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void voicerec_classifySound::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void voicerec_classifySound::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_fu_278_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void voicerec_classifySound::thread_ap_return() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_fu_278_p2.read()))) {
        ap_return = guess_i_reg_137.read();
    } else {
        ap_return = ap_return_preg.read();
    }
}

void voicerec_classifySound::thread_ap_sig_bdd_104() {
    ap_sig_bdd_104 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(6, 6));
}

void voicerec_classifySound::thread_ap_sig_bdd_113() {
    ap_sig_bdd_113 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(7, 7));
}

void voicerec_classifySound::thread_ap_sig_bdd_122() {
    ap_sig_bdd_122 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(8, 8));
}

void voicerec_classifySound::thread_ap_sig_bdd_164() {
    ap_sig_bdd_164 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void voicerec_classifySound::thread_ap_sig_bdd_175() {
    ap_sig_bdd_175 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(4, 4));
}

void voicerec_classifySound::thread_ap_sig_bdd_27() {
    ap_sig_bdd_27 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void voicerec_classifySound::thread_ap_sig_bdd_56() {
    ap_sig_bdd_56 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void voicerec_classifySound::thread_ap_sig_bdd_73() {
    ap_sig_bdd_73 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void voicerec_classifySound::thread_ap_sig_bdd_89() {
    ap_sig_bdd_89 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(5, 5));
}

void voicerec_classifySound::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_27.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void voicerec_classifySound::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_bdd_56.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void voicerec_classifySound::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_bdd_73.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void voicerec_classifySound::thread_ap_sig_cseq_ST_st4_fsm_3() {
    if (ap_sig_bdd_164.read()) {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    }
}

void voicerec_classifySound::thread_ap_sig_cseq_ST_st5_fsm_4() {
    if (ap_sig_bdd_175.read()) {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    }
}

void voicerec_classifySound::thread_ap_sig_cseq_ST_st6_fsm_5() {
    if (ap_sig_bdd_89.read()) {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    }
}

void voicerec_classifySound::thread_ap_sig_cseq_ST_st7_fsm_6() {
    if (ap_sig_bdd_104.read()) {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    }
}

void voicerec_classifySound::thread_ap_sig_cseq_ST_st8_fsm_7() {
    if (ap_sig_bdd_113.read()) {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_0;
    }
}

void voicerec_classifySound::thread_ap_sig_cseq_ST_st9_fsm_8() {
    if (ap_sig_bdd_122.read()) {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_0;
    }
}

void voicerec_classifySound::thread_exitcond1_fu_181_p2() {
    exitcond1_fu_181_p2 = (!i_reg_104.read().is_01() || !ap_const_lv6_3F.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_104.read() == ap_const_lv6_3F);
}

void voicerec_classifySound::thread_exitcond_fu_231_p2() {
    exitcond_fu_231_p2 = (!j_reg_115.read().is_01() || !ap_const_lv4_E.is_01())? sc_lv<1>(): sc_lv<1>(j_reg_115.read() == ap_const_lv4_E);
}

void voicerec_classifySound::thread_exitcond_i_fu_278_p2() {
    exitcond_i_fu_278_p2 = (!guess_reg_126.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(guess_reg_126.read() == ap_const_lv3_4);
}

void voicerec_classifySound::thread_flatInput_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        flatInput_address0 =  (sc_lv<10>) (tmp_3_fu_269_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        flatInput_address0 = grp_voicerec_feedForward_fu_161_pattern_address0.read();
    } else {
        flatInput_address0 = "XXXXXXXXXX";
    }
}

void voicerec_classifySound::thread_flatInput_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        flatInput_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        flatInput_ce0 = grp_voicerec_feedForward_fu_161_pattern_ce0.read();
    } else {
        flatInput_ce0 = ap_const_logic_0;
    }
}

void voicerec_classifySound::thread_flatInput_d0() {
    flatInput_d0 = result_q0.read();
}

void voicerec_classifySound::thread_flatInput_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()))) {
        flatInput_we0 = ap_const_logic_1;
    } else {
        flatInput_we0 = ap_const_logic_0;
    }
}

void voicerec_classifySound::thread_grp_voicerec_feedForward_fu_161_ap_start() {
    grp_voicerec_feedForward_fu_161_ap_start = grp_voicerec_feedForward_fu_161_ap_start_ap_start_reg.read();
}

void voicerec_classifySound::thread_grp_voicerec_feedForward_fu_161_pattern_q0() {
    grp_voicerec_feedForward_fu_161_pattern_q0 = flatInput_q0.read();
}

void voicerec_classifySound::thread_guess_1_fu_377_p3() {
    guess_1_fu_377_p3 = (!tmp_10_fu_372_p2.read()[0].is_01())? sc_lv<32>(): ((tmp_10_fu_372_p2.read()[0].to_bool())? guess_cast1_reg_427.read(): guess_i_reg_137.read());
}

void voicerec_classifySound::thread_guess_cast1_fu_274_p1() {
    guess_cast1_fu_274_p1 = esl_zext<32,3>(guess_reg_126.read());
}

void voicerec_classifySound::thread_i_1_fu_187_p2() {
    i_1_fu_187_p2 = (!i_reg_104.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(i_reg_104.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void voicerec_classifySound::thread_j_1_fu_237_p2() {
    j_1_fu_237_p2 = (!j_reg_115.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(j_reg_115.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void voicerec_classifySound::thread_j_2_fu_284_p2() {
    j_2_fu_284_p2 = (!guess_reg_126.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(guess_reg_126.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void voicerec_classifySound::thread_j_cast3_fu_227_p1() {
    j_cast3_fu_227_p1 = esl_zext<11,4>(j_reg_115.read());
}

void voicerec_classifySound::thread_max_1_fu_384_p3() {
    max_1_fu_384_p3 = (!tmp_10_fu_372_p2.read()[0].is_01())? sc_lv<32>(): ((tmp_10_fu_372_p2.read()[0].to_bool())? max_reg_445.read(): second_max_reg_149.read());
}

void voicerec_classifySound::thread_max_to_int_fu_295_p1() {
    max_to_int_fu_295_p1 = max_reg_445.read();
}

void voicerec_classifySound::thread_notlhs6_fu_348_p2() {
    notlhs6_fu_348_p2 = (!tmp_5_fu_316_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_5_fu_316_p4.read() != ap_const_lv8_FF);
}

void voicerec_classifySound::thread_notlhs_fu_330_p2() {
    notlhs_fu_330_p2 = (!tmp_fu_298_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_fu_298_p4.read() != ap_const_lv8_FF);
}

void voicerec_classifySound::thread_notrhs7_fu_354_p2() {
    notrhs7_fu_354_p2 = (!tmp_4_fu_326_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_4_fu_326_p1.read() == ap_const_lv23_0);
}

void voicerec_classifySound::thread_notrhs_fu_336_p2() {
    notrhs_fu_336_p2 = (!tmp_1_fu_308_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_1_fu_308_p1.read() == ap_const_lv23_0);
}

void voicerec_classifySound::thread_output_r_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        output_r_address0 =  (sc_lv<2>) (tmp_i_fu_290_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        output_r_address0 = grp_voicerec_feedForward_fu_161_output_r_address0.read();
    } else {
        output_r_address0 =  (sc_lv<2>) ("XX");
    }
}

void voicerec_classifySound::thread_output_r_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        output_r_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        output_r_ce0 = grp_voicerec_feedForward_fu_161_output_r_ce0.read();
    } else {
        output_r_ce0 = ap_const_logic_0;
    }
}

void voicerec_classifySound::thread_output_r_d0() {
    output_r_d0 = grp_voicerec_feedForward_fu_161_output_r_d0.read();
}

void voicerec_classifySound::thread_output_r_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        output_r_we0 = grp_voicerec_feedForward_fu_161_output_r_we0.read();
    } else {
        output_r_we0 = ap_const_logic_0;
    }
}

void voicerec_classifySound::thread_p_shl2_cast_fu_213_p1() {
    p_shl2_cast_fu_213_p1 = esl_zext<11,7>(p_shl2_fu_205_p3.read());
}

void voicerec_classifySound::thread_p_shl2_fu_205_p3() {
    p_shl2_fu_205_p3 = esl_concat<6,1>(i_reg_104.read(), ap_const_lv1_0);
}

void voicerec_classifySound::thread_p_shl_cast_fu_201_p1() {
    p_shl_cast_fu_201_p1 = esl_zext<11,10>(p_shl_fu_193_p3.read());
}

void voicerec_classifySound::thread_p_shl_fu_193_p3() {
    p_shl_fu_193_p3 = esl_concat<6,4>(i_reg_104.read(), ap_const_lv4_0);
}

void voicerec_classifySound::thread_result_addr1_cast_fu_223_p1() {
    result_addr1_cast_fu_223_p1 = esl_sext<12,11>(tmp_9_fu_217_p2.read());
}

void voicerec_classifySound::thread_result_addr2_cast_fu_252_p1() {
    result_addr2_cast_fu_252_p1 = esl_sext<32,12>(result_addr2_fu_247_p2.read());
}

void voicerec_classifySound::thread_result_addr2_fu_247_p2() {
    result_addr2_fu_247_p2 = (!tmp_1_trn_cast_fu_243_p1.read().is_01() || !result_addr1_cast_reg_404.read().is_01())? sc_lv<12>(): (sc_biguint<12>(tmp_1_trn_cast_fu_243_p1.read()) + sc_bigint<12>(result_addr1_cast_reg_404.read()));
}

void voicerec_classifySound::thread_result_address0() {
    result_address0 =  (sc_lv<10>) (tmp_11_fu_256_p1.read());
}

void voicerec_classifySound::thread_result_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        result_ce0 = ap_const_logic_1;
    } else {
        result_ce0 = ap_const_logic_0;
    }
}

void voicerec_classifySound::thread_second_max_to_int_fu_312_p1() {
    second_max_to_int_fu_312_p1 = second_max_reg_149.read();
}

void voicerec_classifySound::thread_tmp_10_fu_372_p2() {
    tmp_10_fu_372_p2 = (tmp_s_fu_366_p2.read() & tmp_6_reg_452.read());
}

void voicerec_classifySound::thread_tmp_11_fu_256_p1() {
    tmp_11_fu_256_p1 = esl_zext<64,32>(result_addr2_cast_fu_252_p1.read());
}

void voicerec_classifySound::thread_tmp_1_fu_308_p1() {
    tmp_1_fu_308_p1 = max_to_int_fu_295_p1.read().range(23-1, 0);
}

void voicerec_classifySound::thread_tmp_1_trn_cast_fu_243_p1() {
    tmp_1_trn_cast_fu_243_p1 = esl_zext<12,4>(j_reg_115.read());
}

void voicerec_classifySound::thread_tmp_2_cast_fu_266_p1() {
    tmp_2_cast_fu_266_p1 = esl_sext<32,11>(tmp_2_reg_422.read());
}

void voicerec_classifySound::thread_tmp_2_fu_261_p2() {
    tmp_2_fu_261_p2 = (!tmp_9_reg_399.read().is_01() || !j_cast3_fu_227_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(tmp_9_reg_399.read()) + sc_biguint<11>(j_cast3_fu_227_p1.read()));
}

void voicerec_classifySound::thread_tmp_3_fu_269_p1() {
    tmp_3_fu_269_p1 = esl_zext<64,32>(tmp_2_cast_fu_266_p1.read());
}

void voicerec_classifySound::thread_tmp_4_fu_326_p1() {
    tmp_4_fu_326_p1 = second_max_to_int_fu_312_p1.read().range(23-1, 0);
}

void voicerec_classifySound::thread_tmp_5_fu_316_p4() {
    tmp_5_fu_316_p4 = second_max_to_int_fu_312_p1.read().range(30, 23);
}

void voicerec_classifySound::thread_tmp_6_fu_176_opcode() {
    tmp_6_fu_176_opcode = ap_const_lv5_2;
}

void voicerec_classifySound::thread_tmp_6_fu_176_p0() {
    tmp_6_fu_176_p0 = max_reg_445.read();
}

void voicerec_classifySound::thread_tmp_6_fu_176_p1() {
    tmp_6_fu_176_p1 = second_max_reg_149.read();
}

void voicerec_classifySound::thread_tmp_7_fu_342_p2() {
    tmp_7_fu_342_p2 = (notrhs_fu_336_p2.read() | notlhs_fu_330_p2.read());
}

void voicerec_classifySound::thread_tmp_8_fu_360_p2() {
    tmp_8_fu_360_p2 = (notrhs7_fu_354_p2.read() | notlhs6_fu_348_p2.read());
}

void voicerec_classifySound::thread_tmp_9_fu_217_p2() {
    tmp_9_fu_217_p2 = (!p_shl_cast_fu_201_p1.read().is_01() || !p_shl2_cast_fu_213_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(p_shl_cast_fu_201_p1.read()) - sc_biguint<11>(p_shl2_cast_fu_213_p1.read()));
}

void voicerec_classifySound::thread_tmp_fu_298_p4() {
    tmp_fu_298_p4 = max_to_int_fu_295_p1.read().range(30, 23);
}

void voicerec_classifySound::thread_tmp_i_fu_290_p1() {
    tmp_i_fu_290_p1 = esl_zext<64,3>(guess_reg_126.read());
}

void voicerec_classifySound::thread_tmp_s_fu_366_p2() {
    tmp_s_fu_366_p2 = (tmp_7_fu_342_p2.read() & tmp_8_fu_360_p2.read());
}

void voicerec_classifySound::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (esl_seteq<1,1,1>(exitcond1_fu_181_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            } else {
                ap_NS_fsm = ap_ST_st5_fsm_4;
            }
            break;
        case 4 : 
            if (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_231_p2.read())) {
                ap_NS_fsm = ap_ST_st4_fsm_3;
            } else {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_st3_fsm_2;
            break;
        case 16 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_0, grp_voicerec_feedForward_fu_161_ap_done.read())) {
                ap_NS_fsm = ap_ST_st6_fsm_5;
            } else {
                ap_NS_fsm = ap_ST_st5_fsm_4;
            }
            break;
        case 32 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_fu_278_p2.read())) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st7_fsm_6;
            }
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_st8_fsm_7;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_st9_fsm_8;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_st6_fsm_5;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<9>) ("XXXXXXXXX");
            break;
    }
}

}

