// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.3
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module voicerec_preprocessSound (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_inSound_AWVALID,
        m_axi_inSound_AWREADY,
        m_axi_inSound_AWADDR,
        m_axi_inSound_AWID,
        m_axi_inSound_AWLEN,
        m_axi_inSound_AWSIZE,
        m_axi_inSound_AWBURST,
        m_axi_inSound_AWLOCK,
        m_axi_inSound_AWCACHE,
        m_axi_inSound_AWPROT,
        m_axi_inSound_AWQOS,
        m_axi_inSound_AWREGION,
        m_axi_inSound_AWUSER,
        m_axi_inSound_WVALID,
        m_axi_inSound_WREADY,
        m_axi_inSound_WDATA,
        m_axi_inSound_WSTRB,
        m_axi_inSound_WLAST,
        m_axi_inSound_WID,
        m_axi_inSound_WUSER,
        m_axi_inSound_ARVALID,
        m_axi_inSound_ARREADY,
        m_axi_inSound_ARADDR,
        m_axi_inSound_ARID,
        m_axi_inSound_ARLEN,
        m_axi_inSound_ARSIZE,
        m_axi_inSound_ARBURST,
        m_axi_inSound_ARLOCK,
        m_axi_inSound_ARCACHE,
        m_axi_inSound_ARPROT,
        m_axi_inSound_ARQOS,
        m_axi_inSound_ARREGION,
        m_axi_inSound_ARUSER,
        m_axi_inSound_RVALID,
        m_axi_inSound_RREADY,
        m_axi_inSound_RDATA,
        m_axi_inSound_RLAST,
        m_axi_inSound_RID,
        m_axi_inSound_RUSER,
        m_axi_inSound_RRESP,
        m_axi_inSound_BVALID,
        m_axi_inSound_BREADY,
        m_axi_inSound_BRESP,
        m_axi_inSound_BID,
        m_axi_inSound_BUSER,
        outSound_address0,
        outSound_ce0,
        outSound_we0,
        outSound_d0
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 41'b1;
parameter    ap_ST_st2_fsm_1 = 41'b10;
parameter    ap_ST_st3_fsm_2 = 41'b100;
parameter    ap_ST_st4_fsm_3 = 41'b1000;
parameter    ap_ST_st5_fsm_4 = 41'b10000;
parameter    ap_ST_st6_fsm_5 = 41'b100000;
parameter    ap_ST_st7_fsm_6 = 41'b1000000;
parameter    ap_ST_st8_fsm_7 = 41'b10000000;
parameter    ap_ST_st9_fsm_8 = 41'b100000000;
parameter    ap_ST_st10_fsm_9 = 41'b1000000000;
parameter    ap_ST_st11_fsm_10 = 41'b10000000000;
parameter    ap_ST_st12_fsm_11 = 41'b100000000000;
parameter    ap_ST_st13_fsm_12 = 41'b1000000000000;
parameter    ap_ST_st14_fsm_13 = 41'b10000000000000;
parameter    ap_ST_st15_fsm_14 = 41'b100000000000000;
parameter    ap_ST_st16_fsm_15 = 41'b1000000000000000;
parameter    ap_ST_st17_fsm_16 = 41'b10000000000000000;
parameter    ap_ST_st18_fsm_17 = 41'b100000000000000000;
parameter    ap_ST_st19_fsm_18 = 41'b1000000000000000000;
parameter    ap_ST_st20_fsm_19 = 41'b10000000000000000000;
parameter    ap_ST_st21_fsm_20 = 41'b100000000000000000000;
parameter    ap_ST_st22_fsm_21 = 41'b1000000000000000000000;
parameter    ap_ST_st23_fsm_22 = 41'b10000000000000000000000;
parameter    ap_ST_st24_fsm_23 = 41'b100000000000000000000000;
parameter    ap_ST_st25_fsm_24 = 41'b1000000000000000000000000;
parameter    ap_ST_st26_fsm_25 = 41'b10000000000000000000000000;
parameter    ap_ST_st27_fsm_26 = 41'b100000000000000000000000000;
parameter    ap_ST_st28_fsm_27 = 41'b1000000000000000000000000000;
parameter    ap_ST_st29_fsm_28 = 41'b10000000000000000000000000000;
parameter    ap_ST_st30_fsm_29 = 41'b100000000000000000000000000000;
parameter    ap_ST_st31_fsm_30 = 41'b1000000000000000000000000000000;
parameter    ap_ST_st32_fsm_31 = 41'b10000000000000000000000000000000;
parameter    ap_ST_st33_fsm_32 = 41'b100000000000000000000000000000000;
parameter    ap_ST_st34_fsm_33 = 41'b1000000000000000000000000000000000;
parameter    ap_ST_st35_fsm_34 = 41'b10000000000000000000000000000000000;
parameter    ap_ST_st36_fsm_35 = 41'b100000000000000000000000000000000000;
parameter    ap_ST_st37_fsm_36 = 41'b1000000000000000000000000000000000000;
parameter    ap_ST_st38_fsm_37 = 41'b10000000000000000000000000000000000000;
parameter    ap_ST_st39_fsm_38 = 41'b100000000000000000000000000000000000000;
parameter    ap_ST_st40_fsm_39 = 41'b1000000000000000000000000000000000000000;
parameter    ap_ST_st41_fsm_40 = 41'b10000000000000000000000000000000000000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_10 = 32'b10000;
parameter    ap_const_lv32_19 = 32'b11001;
parameter    ap_const_lv32_27 = 32'b100111;
parameter    ap_const_lv32_7 = 32'b111;
parameter    ap_const_lv32_9 = 32'b1001;
parameter    ap_const_lv32_A = 32'b1010;
parameter    ap_const_lv32_11 = 32'b10001;
parameter    ap_const_lv32_13 = 32'b10011;
parameter    ap_const_lv32_1A = 32'b11010;
parameter    ap_const_lv32_1B = 32'b11011;
parameter    ap_const_lv32_21 = 32'b100001;
parameter    ap_const_lv14_0 = 14'b00000000000000;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv14_3E80 = 14'b11111010000000;
parameter    ap_const_lv32_12 = 32'b10010;
parameter    ap_const_lv15_0 = 15'b000000000000000;
parameter    ap_const_lv32_20 = 32'b100000;
parameter    ap_const_lv32_28 = 32'b101000;
parameter    ap_const_lv32_3E80 = 32'b11111010000000;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv4_0 = 4'b0000;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_1C = 32'b11100;
parameter    ap_const_lv64_0 = 64'b0000000000000000000000000000000000000000000000000000000000000000;
parameter    ap_const_lv8_FF = 8'b11111111;
parameter    ap_const_lv64_3FC3333333333333 = 64'b11111111000011001100110011001100110011001100110011001100110011;
parameter    ap_const_lv14_1 = 14'b1;
parameter    ap_const_lv32_34 = 32'b110100;
parameter    ap_const_lv32_3E = 32'b111110;
parameter    ap_const_lv11_7FF = 11'b11111111111;
parameter    ap_const_lv52_0 = 52'b0000000000000000000000000000000000000000000000000000;
parameter    ap_const_lv15_7FFF = 15'b111111111111111;
parameter    ap_const_lv32_C8 = 32'b11001000;
parameter    ap_const_lv32_1F40 = 32'b1111101000000;
parameter    ap_const_lv32_1F3F = 32'b1111100111111;
parameter    ap_const_lv5_2 = 5'b10;
parameter    ap_const_lv5_4 = 5'b100;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_inSound_AWVALID;
input   m_axi_inSound_AWREADY;
output  [31:0] m_axi_inSound_AWADDR;
output  [0:0] m_axi_inSound_AWID;
output  [31:0] m_axi_inSound_AWLEN;
output  [2:0] m_axi_inSound_AWSIZE;
output  [1:0] m_axi_inSound_AWBURST;
output  [1:0] m_axi_inSound_AWLOCK;
output  [3:0] m_axi_inSound_AWCACHE;
output  [2:0] m_axi_inSound_AWPROT;
output  [3:0] m_axi_inSound_AWQOS;
output  [3:0] m_axi_inSound_AWREGION;
output  [0:0] m_axi_inSound_AWUSER;
output   m_axi_inSound_WVALID;
input   m_axi_inSound_WREADY;
output  [63:0] m_axi_inSound_WDATA;
output  [7:0] m_axi_inSound_WSTRB;
output   m_axi_inSound_WLAST;
output  [0:0] m_axi_inSound_WID;
output  [0:0] m_axi_inSound_WUSER;
output   m_axi_inSound_ARVALID;
input   m_axi_inSound_ARREADY;
output  [31:0] m_axi_inSound_ARADDR;
output  [0:0] m_axi_inSound_ARID;
output  [31:0] m_axi_inSound_ARLEN;
output  [2:0] m_axi_inSound_ARSIZE;
output  [1:0] m_axi_inSound_ARBURST;
output  [1:0] m_axi_inSound_ARLOCK;
output  [3:0] m_axi_inSound_ARCACHE;
output  [2:0] m_axi_inSound_ARPROT;
output  [3:0] m_axi_inSound_ARQOS;
output  [3:0] m_axi_inSound_ARREGION;
output  [0:0] m_axi_inSound_ARUSER;
input   m_axi_inSound_RVALID;
output   m_axi_inSound_RREADY;
input  [63:0] m_axi_inSound_RDATA;
input   m_axi_inSound_RLAST;
input  [0:0] m_axi_inSound_RID;
input  [0:0] m_axi_inSound_RUSER;
input  [1:0] m_axi_inSound_RRESP;
input   m_axi_inSound_BVALID;
output   m_axi_inSound_BREADY;
input  [1:0] m_axi_inSound_BRESP;
input  [0:0] m_axi_inSound_BID;
input  [0:0] m_axi_inSound_BUSER;
output  [12:0] outSound_address0;
output   outSound_ce0;
output   outSound_we0;
output  [63:0] outSound_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_inSound_AWVALID;
reg m_axi_inSound_WVALID;
reg m_axi_inSound_ARVALID;
reg[31:0] m_axi_inSound_ARADDR;
reg[31:0] m_axi_inSound_ARLEN;
reg m_axi_inSound_RREADY;
reg m_axi_inSound_BREADY;
reg[12:0] outSound_address0;
reg outSound_ce0;
reg outSound_we0;
reg[63:0] outSound_d0;
(* fsm_encoding = "none" *) reg   [40:0] ap_CS_fsm = 41'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_59;
reg   [63:0] reg_258;
reg    ap_sig_cseq_ST_st7_fsm_6;
reg    ap_sig_bdd_129;
wire   [0:0] tmp_fu_264_p2;
reg    ap_sig_bdd_137;
reg    ap_sig_cseq_ST_st17_fsm_16;
reg    ap_sig_bdd_146;
reg    ap_sig_cseq_ST_st26_fsm_25;
reg    ap_sig_bdd_156;
reg    ap_sig_cseq_ST_st40_fsm_39;
reg    ap_sig_bdd_165;
reg   [0:0] tmp_reg_756;
wire   [13:0] i_fu_270_p2;
reg   [13:0] i_reg_760;
wire   [0:0] tmp_19_fu_312_p2;
reg   [0:0] tmp_19_reg_765;
reg    ap_sig_cseq_ST_st8_fsm_7;
reg    ap_sig_bdd_179;
wire  signed [14:0] last_2_fu_322_p2;
reg  signed [14:0] last_2_reg_769;
reg    ap_sig_cseq_ST_st10_fsm_9;
reg    ap_sig_bdd_188;
wire  signed [31:0] last_2_cast5_fu_328_p1;
reg  signed [31:0] last_2_cast5_reg_774;
wire   [13:0] tmp_25_fu_332_p1;
reg   [13:0] tmp_25_reg_779;
wire   [0:0] tmp_47_fu_336_p2;
reg   [0:0] tmp_47_reg_784;
reg    ap_sig_cseq_ST_st11_fsm_10;
reg    ap_sig_bdd_203;
reg    ap_sig_ioackin_m_axi_inSound_ARREADY;
wire   [0:0] tmp_24_fu_388_p2;
reg   [0:0] tmp_24_reg_794;
reg    ap_sig_cseq_ST_st18_fsm_17;
reg    ap_sig_bdd_216;
wire   [13:0] i_5_fu_404_p2;
reg   [13:0] i_5_reg_822;
reg    ap_sig_cseq_ST_st20_fsm_19;
reg    ap_sig_bdd_225;
wire   [0:0] exitcond1_fu_398_p2;
wire   [0:0] or_cond_fu_422_p2;
reg   [0:0] or_cond_reg_827;
wire   [0:0] tmp_54_fu_444_p2;
reg   [0:0] tmp_54_reg_844;
reg    ap_sig_cseq_ST_st27_fsm_26;
reg    ap_sig_bdd_247;
wire   [0:0] tmp_36_fu_503_p2;
reg   [0:0] tmp_36_reg_848;
wire   [0:0] tmp_62_fu_512_p2;
reg   [0:0] tmp_62_reg_853;
wire   [13:0] j_8_fu_561_p2;
reg   [13:0] j_8_reg_860;
reg    ap_sig_cseq_ST_st28_fsm_27;
reg    ap_sig_bdd_264;
wire   [0:0] exitcond_fu_555_p2;
wire   [0:0] or_cond4_fu_585_p2;
reg    ap_sig_ioackin_m_axi_inSound_AWREADY;
reg   [0:0] or_cond4_reg_865;
wire   [13:0] i_4_fu_628_p2;
reg   [13:0] i_4_reg_877;
reg    ap_sig_cseq_ST_st34_fsm_33;
reg    ap_sig_bdd_299;
wire   [0:0] exitcond2_fu_622_p2;
wire   [0:0] or_cond6_fu_658_p2;
reg   [0:0] or_cond6_reg_882;
reg   [13:0] first_reg_138;
reg    ap_sig_cseq_ST_st6_fsm_5;
reg    ap_sig_bdd_322;
reg    ap_sig_cseq_ST_st9_fsm_8;
reg    ap_sig_bdd_329;
reg   [13:0] first1_reg_150;
reg   [13:0] i_1_in_reg_163;
reg    ap_sig_cseq_ST_st19_fsm_18;
reg    ap_sig_bdd_352;
reg   [14:0] last_reg_174;
reg   [13:0] markBegin_2_reg_186;
reg   [13:0] j9_reg_198;
reg    ap_sig_cseq_ST_st33_fsm_32;
reg    ap_sig_bdd_388;
reg    ap_sig_bdd_394;
reg   [13:0] i_3_reg_209;
reg    ap_sig_cseq_ST_st41_fsm_40;
reg    ap_sig_bdd_411;
wire  signed [63:0] tmp_59_fu_687_p1;
wire   [0:0] or_cond7_fu_681_p2;
wire  signed [63:0] tmp_60_fu_751_p1;
wire   [0:0] tmp_30_fu_745_p2;
wire   [63:0] tmp_48_fu_342_p1;
wire   [63:0] tmp_57_fu_428_p1;
wire   [63:0] tmp_65_fu_591_p1;
wire   [63:0] tmp_56_fu_664_p1;
reg    ap_reg_ioackin_m_axi_inSound_ARREADY = 1'b0;
reg    ap_reg_ioackin_m_axi_inSound_AWREADY = 1'b0;
reg    ap_reg_ioackin_m_axi_inSound_WREADY = 1'b0;
reg    ap_sig_ioackin_m_axi_inSound_WREADY;
reg    ap_sig_cseq_ST_st29_fsm_28;
reg    ap_sig_bdd_478;
reg   [31:0] deleteFlag_fu_82;
wire   [31:0] p_deleteFlag_fu_533_p3;
reg   [31:0] count_fu_86;
wire   [31:0] count_1_fu_521_p2;
reg   [31:0] markBegin_fu_90;
wire   [31:0] markBegin_1_cast_fu_609_p1;
reg   [31:0] j_1_fu_94;
wire   [31:0] grp_fu_247_p2;
reg   [63:0] grp_fu_220_p0;
wire   [63:0] ret_i_i_i_i_i_fu_470_p1;
wire   [63:0] ret_i_i_i_i_i2_fu_712_p1;
reg   [63:0] grp_fu_220_p1;
wire   [63:0] inSound_load_to_int_fu_276_p1;
wire   [10:0] tmp_15_fu_280_p4;
wire   [51:0] tmp_21_fu_290_p1;
wire   [0:0] notrhs1_fu_300_p2;
wire   [0:0] notlhs1_fu_294_p2;
wire   [0:0] tmp_17_fu_306_p2;
wire   [0:0] grp_fu_220_p2;
wire   [14:0] i_1_in_cast_fu_318_p1;
wire   [63:0] inSound_load_1_to_int_fu_352_p1;
wire   [10:0] tmp_20_fu_356_p4;
wire   [51:0] tmp_26_fu_366_p1;
wire   [0:0] notrhs2_fu_376_p2;
wire   [0:0] notlhs2_fu_370_p2;
wire   [0:0] tmp_22_fu_382_p2;
wire   [14:0] markBegin_2_cast_fu_394_p1;
wire   [0:0] tmp_49_fu_410_p2;
wire   [0:0] tmp_50_fu_416_p2;
wire   [63:0] p_Val2_s_fu_450_p1;
wire   [62:0] tmp_31_fu_454_p1;
wire   [63:0] p_Result_s_fu_462_p3;
wire   [10:0] tmp_33_fu_475_p4;
wire   [51:0] tmp_32_fu_458_p1;
wire   [0:0] notrhs4_fu_491_p2;
wire   [0:0] notlhs4_fu_485_p2;
wire   [0:0] tmp_34_fu_497_p2;
wire   [0:0] tmp_61_fu_527_p2;
wire   [31:0] j9_cast3_fu_551_p1;
wire   [0:0] slt_fu_567_p2;
wire   [0:0] rev_fu_573_p2;
wire   [0:0] tmp_64_fu_579_p2;
wire   [13:0] markBegin_1_fu_602_p3;
wire   [14:0] i_3_cast_fu_618_p1;
wire   [0:0] tmp_52_fu_640_p2;
wire   [0:0] tmp_53_fu_646_p2;
wire   [0:0] tmp1_fu_652_p2;
wire   [0:0] tmp_51_fu_634_p2;
wire   [0:0] tmp_55_fu_675_p2;
wire   [63:0] p_Val2_1_fu_692_p1;
wire   [62:0] tmp_37_fu_696_p1;
wire   [63:0] p_Result_1_fu_704_p3;
wire   [10:0] tmp_27_fu_717_p4;
wire   [51:0] tmp_38_fu_700_p1;
wire   [0:0] notrhs3_fu_733_p2;
wire   [0:0] notlhs3_fu_727_p2;
wire   [0:0] tmp_28_fu_739_p2;
reg   [4:0] grp_fu_220_opcode;
reg   [40:0] ap_NS_fsm;
reg    ap_sig_bdd_434;
reg    ap_sig_bdd_441;
reg    ap_sig_bdd_432;
reg    ap_sig_bdd_436;


voicerec_dcmp_64ns_64ns_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 1 ))
voicerec_dcmp_64ns_64ns_1_1_U1(
    .din0( grp_fu_220_p0 ),
    .din1( grp_fu_220_p1 ),
    .opcode( grp_fu_220_opcode ),
    .dout( grp_fu_220_p2 )
);



/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_reg_ioackin_m_axi_inSound_ARREADY assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ioackin_m_axi_inSound_ARREADY
    if (ap_rst == 1'b1) begin
        ap_reg_ioackin_m_axi_inSound_ARREADY <= ap_const_logic_0;
    end else begin
        if ((((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) & ~(ap_const_logic_0 == ap_sig_ioackin_m_axi_inSound_ARREADY)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st20_fsm_19) & (ap_const_lv1_0 == exitcond1_fu_398_p2) & (ap_const_lv1_0 == or_cond_fu_422_p2) & ~((ap_const_logic_0 == ap_sig_ioackin_m_axi_inSound_ARREADY) & (ap_const_lv1_0 == exitcond1_fu_398_p2) & (ap_const_lv1_0 == or_cond_fu_422_p2))) | ((ap_const_logic_1 == ap_sig_cseq_ST_st34_fsm_33) & (ap_const_lv1_0 == exitcond2_fu_622_p2) & (ap_const_lv1_0 == or_cond6_fu_658_p2) & ~((ap_const_logic_0 == ap_sig_ioackin_m_axi_inSound_ARREADY) & (ap_const_lv1_0 == exitcond2_fu_622_p2) & (ap_const_lv1_0 == or_cond6_fu_658_p2))) | ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~((ap_const_logic_0 == ap_sig_ioackin_m_axi_inSound_ARREADY) | (ap_start == ap_const_logic_0))))) begin
            ap_reg_ioackin_m_axi_inSound_ARREADY <= ap_const_logic_0;
        end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & (ap_const_logic_1 == m_axi_inSound_ARREADY) & ~(ap_start == ap_const_logic_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) & (ap_const_logic_1 == m_axi_inSound_ARREADY)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st20_fsm_19) & (ap_const_lv1_0 == exitcond1_fu_398_p2) & (ap_const_lv1_0 == or_cond_fu_422_p2) & (ap_const_logic_1 == m_axi_inSound_ARREADY)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st34_fsm_33) & (ap_const_lv1_0 == exitcond2_fu_622_p2) & (ap_const_lv1_0 == or_cond6_fu_658_p2) & (ap_const_logic_1 == m_axi_inSound_ARREADY)))) begin
            ap_reg_ioackin_m_axi_inSound_ARREADY <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ioackin_m_axi_inSound_AWREADY assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ioackin_m_axi_inSound_AWREADY
    if (ap_rst == 1'b1) begin
        ap_reg_ioackin_m_axi_inSound_AWREADY <= ap_const_logic_0;
    end else begin
        if (ap_sig_bdd_434) begin
            if (~((ap_const_lv1_0 == or_cond_reg_827) & (ap_const_lv1_0 == tmp_54_reg_844) & (ap_const_lv1_0 == tmp_36_reg_848) & ~(ap_const_lv1_0 == tmp_62_reg_853) & (ap_const_lv1_0 == exitcond_fu_555_p2) & ~(ap_const_lv1_0 == or_cond4_fu_585_p2) & (ap_const_logic_0 == ap_sig_ioackin_m_axi_inSound_AWREADY))) begin
                ap_reg_ioackin_m_axi_inSound_AWREADY <= ap_const_logic_0;
            end else if ((ap_const_logic_1 == m_axi_inSound_AWREADY)) begin
                ap_reg_ioackin_m_axi_inSound_AWREADY <= ap_const_logic_1;
            end
        end
    end
end

/// ap_reg_ioackin_m_axi_inSound_WREADY assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ioackin_m_axi_inSound_WREADY
    if (ap_rst == 1'b1) begin
        ap_reg_ioackin_m_axi_inSound_WREADY <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_cseq_ST_st29_fsm_28)) begin
            if (~(ap_const_logic_0 == ap_sig_ioackin_m_axi_inSound_WREADY)) begin
                ap_reg_ioackin_m_axi_inSound_WREADY <= ap_const_logic_0;
            end else if ((ap_const_logic_1 == m_axi_inSound_WREADY)) begin
                ap_reg_ioackin_m_axi_inSound_WREADY <= ap_const_logic_1;
            end
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st27_fsm_26) & (ap_const_lv1_0 == tmp_54_fu_444_p2) & ~(ap_const_lv1_0 == tmp_36_fu_503_p2))) begin
        count_fu_86 <= count_1_fu_521_p2;
    end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st19_fsm_18) & (~(ap_const_lv1_0 == tmp_24_reg_794) | ~(ap_const_lv1_0 == tmp_47_reg_784))) | ((ap_const_logic_1 == ap_sig_cseq_ST_st28_fsm_27) & ~((ap_const_lv1_0 == or_cond_reg_827) & (ap_const_lv1_0 == tmp_54_reg_844) & (ap_const_lv1_0 == tmp_36_reg_848) & ~(ap_const_lv1_0 == tmp_62_reg_853) & (ap_const_lv1_0 == exitcond_fu_555_p2) & ~(ap_const_lv1_0 == or_cond4_fu_585_p2) & (ap_const_logic_0 == ap_sig_ioackin_m_axi_inSound_AWREADY)) & (((ap_const_lv1_0 == or_cond_reg_827) & (ap_const_lv1_0 == tmp_54_reg_844) & (ap_const_lv1_0 == tmp_36_reg_848) & (ap_const_lv1_0 == tmp_62_reg_853)) | ((ap_const_lv1_0 == or_cond_reg_827) & (ap_const_lv1_0 == tmp_54_reg_844) & (ap_const_lv1_0 == tmp_36_reg_848) & ~(ap_const_lv1_0 == exitcond_fu_555_p2)))))) begin
        count_fu_86 <= ap_const_lv32_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st27_fsm_26) & (ap_const_lv1_0 == tmp_54_fu_444_p2) & ~(ap_const_lv1_0 == tmp_36_fu_503_p2))) begin
        deleteFlag_fu_82 <= p_deleteFlag_fu_533_p3;
    end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st19_fsm_18) & (~(ap_const_lv1_0 == tmp_24_reg_794) | ~(ap_const_lv1_0 == tmp_47_reg_784))) | ((ap_const_logic_1 == ap_sig_cseq_ST_st28_fsm_27) & ~((ap_const_lv1_0 == or_cond_reg_827) & (ap_const_lv1_0 == tmp_54_reg_844) & (ap_const_lv1_0 == tmp_36_reg_848) & ~(ap_const_lv1_0 == tmp_62_reg_853) & (ap_const_lv1_0 == exitcond_fu_555_p2) & ~(ap_const_lv1_0 == or_cond4_fu_585_p2) & (ap_const_logic_0 == ap_sig_ioackin_m_axi_inSound_AWREADY)) & (((ap_const_lv1_0 == or_cond_reg_827) & (ap_const_lv1_0 == tmp_54_reg_844) & (ap_const_lv1_0 == tmp_36_reg_848) & (ap_const_lv1_0 == tmp_62_reg_853)) | ((ap_const_lv1_0 == or_cond_reg_827) & (ap_const_lv1_0 == tmp_54_reg_844) & (ap_const_lv1_0 == tmp_36_reg_848) & ~(ap_const_lv1_0 == exitcond_fu_555_p2)))))) begin
        deleteFlag_fu_82 <= ap_const_lv32_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8) & ~(ap_const_lv1_0 == tmp_reg_756) & ~(ap_const_lv1_0 == tmp_19_reg_765))) begin
        first1_reg_150 <= first_reg_138;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) & (tmp_fu_264_p2 == ap_const_lv1_0) & ~ap_sig_bdd_137)) begin
        first1_reg_150 <= ap_const_lv14_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8) & (ap_const_lv1_0 == tmp_19_reg_765) & ~(ap_const_lv1_0 == tmp_reg_756))) begin
        first_reg_138 <= i_reg_760;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        first_reg_138 <= ap_const_lv14_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st19_fsm_18) & (ap_const_lv1_0 == tmp_24_reg_794) & (ap_const_lv1_0 == tmp_47_reg_784))) begin
        i_1_in_reg_163 <= tmp_25_reg_779;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8) & ((ap_const_lv1_0 == tmp_reg_756) | ~(ap_const_lv1_0 == tmp_19_reg_765)))) begin
        i_1_in_reg_163 <= ap_const_lv14_3E80;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st41_fsm_40)) begin
        i_3_reg_209 <= i_4_reg_877;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st20_fsm_19) & ~((ap_const_logic_0 == ap_sig_ioackin_m_axi_inSound_ARREADY) & (ap_const_lv1_0 == exitcond1_fu_398_p2) & (ap_const_lv1_0 == or_cond_fu_422_p2)) & ~(ap_const_lv1_0 == exitcond1_fu_398_p2))) begin
        i_3_reg_209 <= ap_const_lv14_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st27_fsm_26) & (ap_const_lv1_0 == tmp_54_fu_444_p2) & (ap_const_lv1_0 == tmp_36_fu_503_p2) & ~(ap_const_lv1_0 == tmp_62_fu_512_p2))) begin
        j9_reg_198 <= ap_const_lv14_0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st33_fsm_32) & ~ap_sig_bdd_394)) begin
        j9_reg_198 <= j_8_reg_860;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st41_fsm_40) & (ap_const_lv1_0 == or_cond6_reg_882) & ~(ap_const_lv1_0 == tmp_30_fu_745_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st34_fsm_33) & (ap_const_lv1_0 == exitcond2_fu_622_p2) & ~((ap_const_logic_0 == ap_sig_ioackin_m_axi_inSound_ARREADY) & (ap_const_lv1_0 == exitcond2_fu_622_p2) & (ap_const_lv1_0 == or_cond6_fu_658_p2)) & ~(ap_const_lv1_0 == or_cond6_fu_658_p2) & (ap_const_lv1_0 == or_cond7_fu_681_p2)))) begin
        j_1_fu_94 <= grp_fu_247_p2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st20_fsm_19) & ~((ap_const_logic_0 == ap_sig_ioackin_m_axi_inSound_ARREADY) & (ap_const_lv1_0 == exitcond1_fu_398_p2) & (ap_const_lv1_0 == or_cond_fu_422_p2)) & ~(ap_const_lv1_0 == exitcond1_fu_398_p2))) begin
        j_1_fu_94 <= ap_const_lv32_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st19_fsm_18) & (ap_const_lv1_0 == tmp_47_reg_784) & ~(ap_const_lv1_0 == tmp_24_reg_794))) begin
        last_reg_174 <= last_2_reg_769;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9) & ~(ap_const_lv1_0 == tmp_47_fu_336_p2))) begin
        last_reg_174 <= ap_const_lv15_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st28_fsm_27) & ~((ap_const_lv1_0 == or_cond_reg_827) & (ap_const_lv1_0 == tmp_54_reg_844) & (ap_const_lv1_0 == tmp_36_reg_848) & ~(ap_const_lv1_0 == tmp_62_reg_853) & (ap_const_lv1_0 == exitcond_fu_555_p2) & ~(ap_const_lv1_0 == or_cond4_fu_585_p2) & (ap_const_logic_0 == ap_sig_ioackin_m_axi_inSound_AWREADY)) & ((ap_const_lv1_0 == tmp_62_reg_853) | ~(ap_const_lv1_0 == or_cond_reg_827) | ~(ap_const_lv1_0 == tmp_54_reg_844) | ~(ap_const_lv1_0 == tmp_36_reg_848) | ~(ap_const_lv1_0 == exitcond_fu_555_p2)))) begin
        markBegin_2_reg_186 <= i_5_reg_822;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st19_fsm_18) & (~(ap_const_lv1_0 == tmp_24_reg_794) | ~(ap_const_lv1_0 == tmp_47_reg_784)))) begin
        markBegin_2_reg_186 <= ap_const_lv14_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st28_fsm_27) & (ap_const_lv1_0 == or_cond_reg_827) & ~((ap_const_lv1_0 == or_cond_reg_827) & (ap_const_lv1_0 == tmp_54_reg_844) & (ap_const_lv1_0 == tmp_36_reg_848) & ~(ap_const_lv1_0 == tmp_62_reg_853) & (ap_const_lv1_0 == exitcond_fu_555_p2) & ~(ap_const_lv1_0 == or_cond4_fu_585_p2) & (ap_const_logic_0 == ap_sig_ioackin_m_axi_inSound_AWREADY)) & ~(ap_const_lv1_0 == tmp_54_reg_844))) begin
                markBegin_fu_90[13 : 0] <= markBegin_1_cast_fu_609_p1[13 : 0];
    end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st19_fsm_18) & (~(ap_const_lv1_0 == tmp_24_reg_794) | ~(ap_const_lv1_0 == tmp_47_reg_784))) | ((ap_const_logic_1 == ap_sig_cseq_ST_st28_fsm_27) & ~((ap_const_lv1_0 == or_cond_reg_827) & (ap_const_lv1_0 == tmp_54_reg_844) & (ap_const_lv1_0 == tmp_36_reg_848) & ~(ap_const_lv1_0 == tmp_62_reg_853) & (ap_const_lv1_0 == exitcond_fu_555_p2) & ~(ap_const_lv1_0 == or_cond4_fu_585_p2) & (ap_const_logic_0 == ap_sig_ioackin_m_axi_inSound_AWREADY)) & (((ap_const_lv1_0 == or_cond_reg_827) & (ap_const_lv1_0 == tmp_54_reg_844) & (ap_const_lv1_0 == tmp_36_reg_848) & (ap_const_lv1_0 == tmp_62_reg_853)) | ((ap_const_lv1_0 == or_cond_reg_827) & (ap_const_lv1_0 == tmp_54_reg_844) & (ap_const_lv1_0 == tmp_36_reg_848) & ~(ap_const_lv1_0 == exitcond_fu_555_p2)))))) begin
        markBegin_fu_90[0] <= 1'b0;
        markBegin_fu_90[1] <= 1'b0;
        markBegin_fu_90[2] <= 1'b0;
        markBegin_fu_90[3] <= 1'b0;
        markBegin_fu_90[4] <= 1'b0;
        markBegin_fu_90[5] <= 1'b0;
        markBegin_fu_90[6] <= 1'b0;
        markBegin_fu_90[7] <= 1'b0;
        markBegin_fu_90[8] <= 1'b0;
        markBegin_fu_90[9] <= 1'b0;
        markBegin_fu_90[10] <= 1'b0;
        markBegin_fu_90[11] <= 1'b0;
        markBegin_fu_90[12] <= 1'b0;
        markBegin_fu_90[13] <= 1'b0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st34_fsm_33) & ~((ap_const_logic_0 == ap_sig_ioackin_m_axi_inSound_ARREADY) & (ap_const_lv1_0 == exitcond2_fu_622_p2) & (ap_const_lv1_0 == or_cond6_fu_658_p2)))) begin
        i_4_reg_877 <= i_4_fu_628_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st20_fsm_19) & ~((ap_const_logic_0 == ap_sig_ioackin_m_axi_inSound_ARREADY) & (ap_const_lv1_0 == exitcond1_fu_398_p2) & (ap_const_lv1_0 == or_cond_fu_422_p2)))) begin
        i_5_reg_822 <= i_5_fu_404_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) & ~ap_sig_bdd_137)) begin
        i_reg_760 <= i_fu_270_p2;
        tmp_reg_756 <= tmp_fu_264_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st28_fsm_27) & (ap_const_lv1_0 == or_cond_reg_827) & (ap_const_lv1_0 == tmp_54_reg_844) & (ap_const_lv1_0 == tmp_36_reg_848) & ~(ap_const_lv1_0 == tmp_62_reg_853) & ~((ap_const_lv1_0 == or_cond_reg_827) & (ap_const_lv1_0 == tmp_54_reg_844) & (ap_const_lv1_0 == tmp_36_reg_848) & ~(ap_const_lv1_0 == tmp_62_reg_853) & (ap_const_lv1_0 == exitcond_fu_555_p2) & ~(ap_const_lv1_0 == or_cond4_fu_585_p2) & (ap_const_logic_0 == ap_sig_ioackin_m_axi_inSound_AWREADY)))) begin
        j_8_reg_860 <= j_8_fu_561_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9)) begin
        last_2_cast5_reg_774 <= last_2_cast5_fu_328_p1;
        last_2_reg_769 <= last_2_fu_322_p2;
        tmp_25_reg_779 <= tmp_25_fu_332_p1;
        tmp_47_reg_784 <= tmp_47_fu_336_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st28_fsm_27) & (ap_const_lv1_0 == or_cond_reg_827) & (ap_const_lv1_0 == tmp_54_reg_844) & (ap_const_lv1_0 == tmp_36_reg_848) & ~(ap_const_lv1_0 == tmp_62_reg_853) & (ap_const_lv1_0 == exitcond_fu_555_p2) & ~((ap_const_lv1_0 == or_cond_reg_827) & (ap_const_lv1_0 == tmp_54_reg_844) & (ap_const_lv1_0 == tmp_36_reg_848) & ~(ap_const_lv1_0 == tmp_62_reg_853) & (ap_const_lv1_0 == exitcond_fu_555_p2) & ~(ap_const_lv1_0 == or_cond4_fu_585_p2) & (ap_const_logic_0 == ap_sig_ioackin_m_axi_inSound_AWREADY)))) begin
        or_cond4_reg_865 <= or_cond4_fu_585_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st34_fsm_33) & (ap_const_lv1_0 == exitcond2_fu_622_p2) & ~((ap_const_logic_0 == ap_sig_ioackin_m_axi_inSound_ARREADY) & (ap_const_lv1_0 == exitcond2_fu_622_p2) & (ap_const_lv1_0 == or_cond6_fu_658_p2)))) begin
        or_cond6_reg_882 <= or_cond6_fu_658_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st20_fsm_19) & (ap_const_lv1_0 == exitcond1_fu_398_p2) & ~((ap_const_logic_0 == ap_sig_ioackin_m_axi_inSound_ARREADY) & (ap_const_lv1_0 == exitcond1_fu_398_p2) & (ap_const_lv1_0 == or_cond_fu_422_p2)))) begin
        or_cond_reg_827 <= or_cond_fu_422_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) & ~(tmp_fu_264_p2 == ap_const_lv1_0) & ~ap_sig_bdd_137) | ((ap_const_logic_1 == ap_sig_cseq_ST_st17_fsm_16) & ~(m_axi_inSound_RVALID == ap_const_logic_0)) | (~(m_axi_inSound_RVALID == ap_const_logic_0) & (ap_const_logic_1 == ap_sig_cseq_ST_st26_fsm_25)) | (~(m_axi_inSound_RVALID == ap_const_logic_0) & (ap_const_logic_1 == ap_sig_cseq_ST_st40_fsm_39)))) begin
        reg_258 <= m_axi_inSound_RDATA;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7)) begin
        tmp_19_reg_765 <= tmp_19_fu_312_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17)) begin
        tmp_24_reg_794 <= tmp_24_fu_388_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st27_fsm_26)) begin
        tmp_36_reg_848 <= tmp_36_fu_503_p2;
        tmp_54_reg_844 <= tmp_54_fu_444_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st27_fsm_26) & (ap_const_lv1_0 == tmp_54_fu_444_p2) & (ap_const_lv1_0 == tmp_36_fu_503_p2))) begin
        tmp_62_reg_853 <= tmp_62_fu_512_p2;
    end
end

/// ap_done assign process. ///
always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0 or ap_sig_ioackin_m_axi_inSound_ARREADY or ap_sig_cseq_ST_st34_fsm_33 or exitcond2_fu_622_p2 or or_cond6_fu_658_p2)
begin
    if (((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st34_fsm_33) & ~((ap_const_logic_0 == ap_sig_ioackin_m_axi_inSound_ARREADY) & (ap_const_lv1_0 == exitcond2_fu_622_p2) & (ap_const_lv1_0 == or_cond6_fu_658_p2)) & ~(ap_const_lv1_0 == exitcond2_fu_622_p2)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (ap_sig_ioackin_m_axi_inSound_ARREADY or ap_sig_cseq_ST_st34_fsm_33 or exitcond2_fu_622_p2 or or_cond6_fu_658_p2)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st34_fsm_33) & ~((ap_const_logic_0 == ap_sig_ioackin_m_axi_inSound_ARREADY) & (ap_const_lv1_0 == exitcond2_fu_622_p2) & (ap_const_lv1_0 == or_cond6_fu_658_p2)) & ~(ap_const_lv1_0 == exitcond2_fu_622_p2))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st10_fsm_9 assign process. ///
always @ (ap_sig_bdd_188)
begin
    if (ap_sig_bdd_188) begin
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st11_fsm_10 assign process. ///
always @ (ap_sig_bdd_203)
begin
    if (ap_sig_bdd_203) begin
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st17_fsm_16 assign process. ///
always @ (ap_sig_bdd_146)
begin
    if (ap_sig_bdd_146) begin
        ap_sig_cseq_ST_st17_fsm_16 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st17_fsm_16 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st18_fsm_17 assign process. ///
always @ (ap_sig_bdd_216)
begin
    if (ap_sig_bdd_216) begin
        ap_sig_cseq_ST_st18_fsm_17 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st18_fsm_17 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st19_fsm_18 assign process. ///
always @ (ap_sig_bdd_352)
begin
    if (ap_sig_bdd_352) begin
        ap_sig_cseq_ST_st19_fsm_18 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st19_fsm_18 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st1_fsm_0 assign process. ///
always @ (ap_sig_bdd_59)
begin
    if (ap_sig_bdd_59) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st20_fsm_19 assign process. ///
always @ (ap_sig_bdd_225)
begin
    if (ap_sig_bdd_225) begin
        ap_sig_cseq_ST_st20_fsm_19 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st20_fsm_19 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st26_fsm_25 assign process. ///
always @ (ap_sig_bdd_156)
begin
    if (ap_sig_bdd_156) begin
        ap_sig_cseq_ST_st26_fsm_25 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st26_fsm_25 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st27_fsm_26 assign process. ///
always @ (ap_sig_bdd_247)
begin
    if (ap_sig_bdd_247) begin
        ap_sig_cseq_ST_st27_fsm_26 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st27_fsm_26 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st28_fsm_27 assign process. ///
always @ (ap_sig_bdd_264)
begin
    if (ap_sig_bdd_264) begin
        ap_sig_cseq_ST_st28_fsm_27 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st28_fsm_27 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st29_fsm_28 assign process. ///
always @ (ap_sig_bdd_478)
begin
    if (ap_sig_bdd_478) begin
        ap_sig_cseq_ST_st29_fsm_28 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st29_fsm_28 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st33_fsm_32 assign process. ///
always @ (ap_sig_bdd_388)
begin
    if (ap_sig_bdd_388) begin
        ap_sig_cseq_ST_st33_fsm_32 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st33_fsm_32 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st34_fsm_33 assign process. ///
always @ (ap_sig_bdd_299)
begin
    if (ap_sig_bdd_299) begin
        ap_sig_cseq_ST_st34_fsm_33 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st34_fsm_33 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st40_fsm_39 assign process. ///
always @ (ap_sig_bdd_165)
begin
    if (ap_sig_bdd_165) begin
        ap_sig_cseq_ST_st40_fsm_39 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st40_fsm_39 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st41_fsm_40 assign process. ///
always @ (ap_sig_bdd_411)
begin
    if (ap_sig_bdd_411) begin
        ap_sig_cseq_ST_st41_fsm_40 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st41_fsm_40 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st6_fsm_5 assign process. ///
always @ (ap_sig_bdd_322)
begin
    if (ap_sig_bdd_322) begin
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st7_fsm_6 assign process. ///
always @ (ap_sig_bdd_129)
begin
    if (ap_sig_bdd_129) begin
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st8_fsm_7 assign process. ///
always @ (ap_sig_bdd_179)
begin
    if (ap_sig_bdd_179) begin
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st9_fsm_8 assign process. ///
always @ (ap_sig_bdd_329)
begin
    if (ap_sig_bdd_329) begin
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_0;
    end
end

/// ap_sig_ioackin_m_axi_inSound_ARREADY assign process. ///
always @ (m_axi_inSound_ARREADY or ap_reg_ioackin_m_axi_inSound_ARREADY)
begin
    if ((ap_const_logic_0 == ap_reg_ioackin_m_axi_inSound_ARREADY)) begin
        ap_sig_ioackin_m_axi_inSound_ARREADY = m_axi_inSound_ARREADY;
    end else begin
        ap_sig_ioackin_m_axi_inSound_ARREADY = ap_const_logic_1;
    end
end

/// ap_sig_ioackin_m_axi_inSound_AWREADY assign process. ///
always @ (m_axi_inSound_AWREADY or ap_reg_ioackin_m_axi_inSound_AWREADY)
begin
    if ((ap_const_logic_0 == ap_reg_ioackin_m_axi_inSound_AWREADY)) begin
        ap_sig_ioackin_m_axi_inSound_AWREADY = m_axi_inSound_AWREADY;
    end else begin
        ap_sig_ioackin_m_axi_inSound_AWREADY = ap_const_logic_1;
    end
end

/// ap_sig_ioackin_m_axi_inSound_WREADY assign process. ///
always @ (m_axi_inSound_WREADY or ap_reg_ioackin_m_axi_inSound_WREADY)
begin
    if ((ap_const_logic_0 == ap_reg_ioackin_m_axi_inSound_WREADY)) begin
        ap_sig_ioackin_m_axi_inSound_WREADY = m_axi_inSound_WREADY;
    end else begin
        ap_sig_ioackin_m_axi_inSound_WREADY = ap_const_logic_1;
    end
end

/// grp_fu_220_opcode assign process. ///
always @ (ap_sig_cseq_ST_st8_fsm_7 or ap_sig_cseq_ST_st18_fsm_17 or ap_sig_cseq_ST_st27_fsm_26 or or_cond6_reg_882 or ap_sig_cseq_ST_st41_fsm_40)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st27_fsm_26)) begin
        grp_fu_220_opcode = ap_const_lv5_4;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) | (ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) | ((ap_const_logic_1 == ap_sig_cseq_ST_st41_fsm_40) & (ap_const_lv1_0 == or_cond6_reg_882)))) begin
        grp_fu_220_opcode = ap_const_lv5_2;
    end else begin
        grp_fu_220_opcode = 'bx;
    end
end

/// grp_fu_220_p0 assign process. ///
always @ (reg_258 or ap_sig_cseq_ST_st8_fsm_7 or ap_sig_cseq_ST_st18_fsm_17 or ap_sig_cseq_ST_st27_fsm_26 or ap_sig_cseq_ST_st41_fsm_40 or ret_i_i_i_i_i_fu_470_p1 or ret_i_i_i_i_i2_fu_712_p1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st41_fsm_40)) begin
        grp_fu_220_p0 = ret_i_i_i_i_i2_fu_712_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st27_fsm_26)) begin
        grp_fu_220_p0 = ret_i_i_i_i_i_fu_470_p1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) | (ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17))) begin
        grp_fu_220_p0 = reg_258;
    end else begin
        grp_fu_220_p0 = 'bx;
    end
end

/// grp_fu_220_p1 assign process. ///
always @ (ap_sig_cseq_ST_st8_fsm_7 or ap_sig_cseq_ST_st18_fsm_17 or ap_sig_cseq_ST_st27_fsm_26 or ap_sig_cseq_ST_st41_fsm_40)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st41_fsm_40)) begin
        grp_fu_220_p1 = ap_const_lv64_0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) | (ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) | (ap_const_logic_1 == ap_sig_cseq_ST_st27_fsm_26))) begin
        grp_fu_220_p1 = ap_const_lv64_3FC3333333333333;
    end else begin
        grp_fu_220_p1 = 'bx;
    end
end

/// m_axi_inSound_ARADDR assign process. ///
always @ (ap_sig_cseq_ST_st11_fsm_10 or tmp_48_fu_342_p1 or tmp_57_fu_428_p1 or tmp_56_fu_664_p1 or ap_reg_ioackin_m_axi_inSound_ARREADY or ap_sig_bdd_441 or ap_sig_bdd_432 or ap_sig_bdd_436)
begin
    if ((ap_const_logic_0 == ap_reg_ioackin_m_axi_inSound_ARREADY)) begin
        if (ap_sig_bdd_436) begin
            m_axi_inSound_ARADDR = tmp_56_fu_664_p1;
        end else if (ap_sig_bdd_432) begin
            m_axi_inSound_ARADDR = tmp_57_fu_428_p1;
        end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10)) begin
            m_axi_inSound_ARADDR = tmp_48_fu_342_p1;
        end else if (ap_sig_bdd_441) begin
            m_axi_inSound_ARADDR = ap_const_lv32_0;
        end else begin
            m_axi_inSound_ARADDR = 'bx;
        end
    end else begin
        m_axi_inSound_ARADDR = 'bx;
    end
end

/// m_axi_inSound_ARLEN assign process. ///
always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0 or ap_sig_cseq_ST_st11_fsm_10 or ap_sig_cseq_ST_st20_fsm_19 or exitcond1_fu_398_p2 or or_cond_fu_422_p2 or ap_sig_cseq_ST_st34_fsm_33 or exitcond2_fu_622_p2 or or_cond6_fu_658_p2 or ap_reg_ioackin_m_axi_inSound_ARREADY)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) & (ap_const_logic_0 == ap_reg_ioackin_m_axi_inSound_ARREADY)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st20_fsm_19) & (ap_const_lv1_0 == exitcond1_fu_398_p2) & (ap_const_lv1_0 == or_cond_fu_422_p2) & (ap_const_logic_0 == ap_reg_ioackin_m_axi_inSound_ARREADY)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st34_fsm_33) & (ap_const_lv1_0 == exitcond2_fu_622_p2) & (ap_const_lv1_0 == or_cond6_fu_658_p2) & (ap_const_logic_0 == ap_reg_ioackin_m_axi_inSound_ARREADY)))) begin
        m_axi_inSound_ARLEN = ap_const_lv32_1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0) & (ap_const_logic_0 == ap_reg_ioackin_m_axi_inSound_ARREADY))) begin
        m_axi_inSound_ARLEN = ap_const_lv32_3E80;
    end else begin
        m_axi_inSound_ARLEN = 'bx;
    end
end

/// m_axi_inSound_ARVALID assign process. ///
always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0 or ap_sig_cseq_ST_st11_fsm_10 or ap_sig_cseq_ST_st20_fsm_19 or exitcond1_fu_398_p2 or or_cond_fu_422_p2 or ap_sig_cseq_ST_st34_fsm_33 or exitcond2_fu_622_p2 or or_cond6_fu_658_p2 or ap_reg_ioackin_m_axi_inSound_ARREADY)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0) & (ap_const_logic_0 == ap_reg_ioackin_m_axi_inSound_ARREADY)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) & (ap_const_logic_0 == ap_reg_ioackin_m_axi_inSound_ARREADY)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st20_fsm_19) & (ap_const_lv1_0 == exitcond1_fu_398_p2) & (ap_const_lv1_0 == or_cond_fu_422_p2) & (ap_const_logic_0 == ap_reg_ioackin_m_axi_inSound_ARREADY)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st34_fsm_33) & (ap_const_lv1_0 == exitcond2_fu_622_p2) & (ap_const_lv1_0 == or_cond6_fu_658_p2) & (ap_const_logic_0 == ap_reg_ioackin_m_axi_inSound_ARREADY)))) begin
        m_axi_inSound_ARVALID = ap_const_logic_1;
    end else begin
        m_axi_inSound_ARVALID = ap_const_logic_0;
    end
end

/// m_axi_inSound_AWVALID assign process. ///
always @ (or_cond_reg_827 or tmp_54_reg_844 or tmp_36_reg_848 or tmp_62_reg_853 or ap_sig_cseq_ST_st28_fsm_27 or exitcond_fu_555_p2 or or_cond4_fu_585_p2 or ap_reg_ioackin_m_axi_inSound_AWREADY)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st28_fsm_27) & (ap_const_lv1_0 == or_cond_reg_827) & (ap_const_lv1_0 == tmp_54_reg_844) & (ap_const_lv1_0 == tmp_36_reg_848) & ~(ap_const_lv1_0 == tmp_62_reg_853) & (ap_const_lv1_0 == exitcond_fu_555_p2) & ~(ap_const_lv1_0 == or_cond4_fu_585_p2) & (ap_const_logic_0 == ap_reg_ioackin_m_axi_inSound_AWREADY))) begin
        m_axi_inSound_AWVALID = ap_const_logic_1;
    end else begin
        m_axi_inSound_AWVALID = ap_const_logic_0;
    end
end

/// m_axi_inSound_BREADY assign process. ///
always @ (or_cond4_reg_865 or ap_sig_cseq_ST_st33_fsm_32 or ap_sig_bdd_394)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st33_fsm_32) & ~(ap_const_lv1_0 == or_cond4_reg_865) & ~ap_sig_bdd_394)) begin
        m_axi_inSound_BREADY = ap_const_logic_1;
    end else begin
        m_axi_inSound_BREADY = ap_const_logic_0;
    end
end

/// m_axi_inSound_RREADY assign process. ///
always @ (m_axi_inSound_RVALID or ap_sig_cseq_ST_st7_fsm_6 or tmp_fu_264_p2 or ap_sig_bdd_137 or ap_sig_cseq_ST_st17_fsm_16 or ap_sig_cseq_ST_st26_fsm_25 or ap_sig_cseq_ST_st40_fsm_39)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) & ~(tmp_fu_264_p2 == ap_const_lv1_0) & ~ap_sig_bdd_137) | ((ap_const_logic_1 == ap_sig_cseq_ST_st17_fsm_16) & ~(m_axi_inSound_RVALID == ap_const_logic_0)) | (~(m_axi_inSound_RVALID == ap_const_logic_0) & (ap_const_logic_1 == ap_sig_cseq_ST_st26_fsm_25)) | (~(m_axi_inSound_RVALID == ap_const_logic_0) & (ap_const_logic_1 == ap_sig_cseq_ST_st40_fsm_39)))) begin
        m_axi_inSound_RREADY = ap_const_logic_1;
    end else begin
        m_axi_inSound_RREADY = ap_const_logic_0;
    end
end

/// m_axi_inSound_WVALID assign process. ///
always @ (ap_reg_ioackin_m_axi_inSound_WREADY or ap_sig_cseq_ST_st29_fsm_28)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st29_fsm_28) & (ap_const_logic_0 == ap_reg_ioackin_m_axi_inSound_WREADY))) begin
        m_axi_inSound_WVALID = ap_const_logic_1;
    end else begin
        m_axi_inSound_WVALID = ap_const_logic_0;
    end
end

/// outSound_address0 assign process. ///
always @ (ap_sig_cseq_ST_st34_fsm_33 or ap_sig_cseq_ST_st41_fsm_40 or tmp_59_fu_687_p1 or tmp_60_fu_751_p1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st41_fsm_40)) begin
        outSound_address0 = tmp_60_fu_751_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st34_fsm_33)) begin
        outSound_address0 = tmp_59_fu_687_p1;
    end else begin
        outSound_address0 = 'bx;
    end
end

/// outSound_ce0 assign process. ///
always @ (ap_sig_ioackin_m_axi_inSound_ARREADY or ap_sig_cseq_ST_st34_fsm_33 or exitcond2_fu_622_p2 or or_cond6_fu_658_p2 or ap_sig_cseq_ST_st41_fsm_40)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st34_fsm_33) & ~((ap_const_logic_0 == ap_sig_ioackin_m_axi_inSound_ARREADY) & (ap_const_lv1_0 == exitcond2_fu_622_p2) & (ap_const_lv1_0 == or_cond6_fu_658_p2))) | (ap_const_logic_1 == ap_sig_cseq_ST_st41_fsm_40))) begin
        outSound_ce0 = ap_const_logic_1;
    end else begin
        outSound_ce0 = ap_const_logic_0;
    end
end

/// outSound_d0 assign process. ///
always @ (reg_258 or ap_sig_cseq_ST_st34_fsm_33 or ap_sig_cseq_ST_st41_fsm_40)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st41_fsm_40)) begin
        outSound_d0 = reg_258;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st34_fsm_33)) begin
        outSound_d0 = ap_const_lv64_0;
    end else begin
        outSound_d0 = 'bx;
    end
end

/// outSound_we0 assign process. ///
always @ (ap_sig_ioackin_m_axi_inSound_ARREADY or ap_sig_cseq_ST_st34_fsm_33 or exitcond2_fu_622_p2 or or_cond6_fu_658_p2 or or_cond6_reg_882 or ap_sig_cseq_ST_st41_fsm_40 or or_cond7_fu_681_p2 or tmp_30_fu_745_p2)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st41_fsm_40) & (ap_const_lv1_0 == or_cond6_reg_882) & ~(ap_const_lv1_0 == tmp_30_fu_745_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st34_fsm_33) & (ap_const_lv1_0 == exitcond2_fu_622_p2) & ~((ap_const_logic_0 == ap_sig_ioackin_m_axi_inSound_ARREADY) & (ap_const_lv1_0 == exitcond2_fu_622_p2) & (ap_const_lv1_0 == or_cond6_fu_658_p2)) & ~(ap_const_lv1_0 == or_cond6_fu_658_p2) & (ap_const_lv1_0 == or_cond7_fu_681_p2)))) begin
        outSound_we0 = ap_const_logic_1;
    end else begin
        outSound_we0 = ap_const_logic_0;
    end
end
/// the next state (ap_NS_fsm) of the state machine. ///
always @ (ap_start or ap_CS_fsm or m_axi_inSound_RVALID or tmp_fu_264_p2 or ap_sig_bdd_137 or tmp_reg_756 or tmp_19_reg_765 or tmp_47_fu_336_p2 or tmp_47_reg_784 or ap_sig_ioackin_m_axi_inSound_ARREADY or tmp_24_reg_794 or exitcond1_fu_398_p2 or or_cond_fu_422_p2 or or_cond_reg_827 or tmp_54_reg_844 or tmp_36_reg_848 or tmp_62_reg_853 or exitcond_fu_555_p2 or or_cond4_fu_585_p2 or ap_sig_ioackin_m_axi_inSound_AWREADY or exitcond2_fu_622_p2 or or_cond6_fu_658_p2 or ap_sig_bdd_394 or ap_sig_ioackin_m_axi_inSound_WREADY)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~((ap_const_logic_0 == ap_sig_ioackin_m_axi_inSound_ARREADY) | (ap_start == ap_const_logic_0))) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : 
        begin
            ap_NS_fsm = ap_ST_st3_fsm_2;
        end
        ap_ST_st3_fsm_2 : 
        begin
            ap_NS_fsm = ap_ST_st4_fsm_3;
        end
        ap_ST_st4_fsm_3 : 
        begin
            ap_NS_fsm = ap_ST_st5_fsm_4;
        end
        ap_ST_st5_fsm_4 : 
        begin
            ap_NS_fsm = ap_ST_st6_fsm_5;
        end
        ap_ST_st6_fsm_5 : 
        begin
            ap_NS_fsm = ap_ST_st7_fsm_6;
        end
        ap_ST_st7_fsm_6 : 
        begin
            if (((tmp_fu_264_p2 == ap_const_lv1_0) & ~ap_sig_bdd_137)) begin
                ap_NS_fsm = ap_ST_st9_fsm_8;
            end else if ((~(tmp_fu_264_p2 == ap_const_lv1_0) & ~ap_sig_bdd_137)) begin
                ap_NS_fsm = ap_ST_st8_fsm_7;
            end else begin
                ap_NS_fsm = ap_ST_st7_fsm_6;
            end
        end
        ap_ST_st8_fsm_7 : 
        begin
            ap_NS_fsm = ap_ST_st9_fsm_8;
        end
        ap_ST_st9_fsm_8 : 
        begin
            if (((ap_const_lv1_0 == tmp_reg_756) | ~(ap_const_lv1_0 == tmp_19_reg_765))) begin
                ap_NS_fsm = ap_ST_st10_fsm_9;
            end else begin
                ap_NS_fsm = ap_ST_st7_fsm_6;
            end
        end
        ap_ST_st10_fsm_9 : 
        begin
            if (~(ap_const_lv1_0 == tmp_47_fu_336_p2)) begin
                ap_NS_fsm = ap_ST_st19_fsm_18;
            end else begin
                ap_NS_fsm = ap_ST_st11_fsm_10;
            end
        end
        ap_ST_st11_fsm_10 : 
        begin
            if (~(ap_const_logic_0 == ap_sig_ioackin_m_axi_inSound_ARREADY)) begin
                ap_NS_fsm = ap_ST_st12_fsm_11;
            end else begin
                ap_NS_fsm = ap_ST_st11_fsm_10;
            end
        end
        ap_ST_st12_fsm_11 : 
        begin
            ap_NS_fsm = ap_ST_st13_fsm_12;
        end
        ap_ST_st13_fsm_12 : 
        begin
            ap_NS_fsm = ap_ST_st14_fsm_13;
        end
        ap_ST_st14_fsm_13 : 
        begin
            ap_NS_fsm = ap_ST_st15_fsm_14;
        end
        ap_ST_st15_fsm_14 : 
        begin
            ap_NS_fsm = ap_ST_st16_fsm_15;
        end
        ap_ST_st16_fsm_15 : 
        begin
            ap_NS_fsm = ap_ST_st17_fsm_16;
        end
        ap_ST_st17_fsm_16 : 
        begin
            if (~(m_axi_inSound_RVALID == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st18_fsm_17;
            end else begin
                ap_NS_fsm = ap_ST_st17_fsm_16;
            end
        end
        ap_ST_st18_fsm_17 : 
        begin
            ap_NS_fsm = ap_ST_st19_fsm_18;
        end
        ap_ST_st19_fsm_18 : 
        begin
            if ((~(ap_const_lv1_0 == tmp_24_reg_794) | ~(ap_const_lv1_0 == tmp_47_reg_784))) begin
                ap_NS_fsm = ap_ST_st20_fsm_19;
            end else begin
                ap_NS_fsm = ap_ST_st10_fsm_9;
            end
        end
        ap_ST_st20_fsm_19 : 
        begin
            if ((~((ap_const_logic_0 == ap_sig_ioackin_m_axi_inSound_ARREADY) & (ap_const_lv1_0 == exitcond1_fu_398_p2) & (ap_const_lv1_0 == or_cond_fu_422_p2)) & ~(ap_const_lv1_0 == exitcond1_fu_398_p2))) begin
                ap_NS_fsm = ap_ST_st34_fsm_33;
            end else if (((ap_const_lv1_0 == exitcond1_fu_398_p2) & ~((ap_const_logic_0 == ap_sig_ioackin_m_axi_inSound_ARREADY) & (ap_const_lv1_0 == exitcond1_fu_398_p2) & (ap_const_lv1_0 == or_cond_fu_422_p2)) & ~(ap_const_lv1_0 == or_cond_fu_422_p2))) begin
                ap_NS_fsm = ap_ST_st28_fsm_27;
            end else if (((ap_const_lv1_0 == exitcond1_fu_398_p2) & (ap_const_lv1_0 == or_cond_fu_422_p2) & ~((ap_const_logic_0 == ap_sig_ioackin_m_axi_inSound_ARREADY) & (ap_const_lv1_0 == exitcond1_fu_398_p2) & (ap_const_lv1_0 == or_cond_fu_422_p2)))) begin
                ap_NS_fsm = ap_ST_st21_fsm_20;
            end else begin
                ap_NS_fsm = ap_ST_st20_fsm_19;
            end
        end
        ap_ST_st21_fsm_20 : 
        begin
            ap_NS_fsm = ap_ST_st22_fsm_21;
        end
        ap_ST_st22_fsm_21 : 
        begin
            ap_NS_fsm = ap_ST_st23_fsm_22;
        end
        ap_ST_st23_fsm_22 : 
        begin
            ap_NS_fsm = ap_ST_st24_fsm_23;
        end
        ap_ST_st24_fsm_23 : 
        begin
            ap_NS_fsm = ap_ST_st25_fsm_24;
        end
        ap_ST_st25_fsm_24 : 
        begin
            ap_NS_fsm = ap_ST_st26_fsm_25;
        end
        ap_ST_st26_fsm_25 : 
        begin
            if (~(m_axi_inSound_RVALID == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st27_fsm_26;
            end else begin
                ap_NS_fsm = ap_ST_st26_fsm_25;
            end
        end
        ap_ST_st27_fsm_26 : 
        begin
            ap_NS_fsm = ap_ST_st28_fsm_27;
        end
        ap_ST_st28_fsm_27 : 
        begin
            if ((~((ap_const_lv1_0 == or_cond_reg_827) & (ap_const_lv1_0 == tmp_54_reg_844) & (ap_const_lv1_0 == tmp_36_reg_848) & ~(ap_const_lv1_0 == tmp_62_reg_853) & (ap_const_lv1_0 == exitcond_fu_555_p2) & ~(ap_const_lv1_0 == or_cond4_fu_585_p2) & (ap_const_logic_0 == ap_sig_ioackin_m_axi_inSound_AWREADY)) & ((ap_const_lv1_0 == tmp_62_reg_853) | ~(ap_const_lv1_0 == or_cond_reg_827) | ~(ap_const_lv1_0 == tmp_54_reg_844) | ~(ap_const_lv1_0 == tmp_36_reg_848) | ~(ap_const_lv1_0 == exitcond_fu_555_p2)))) begin
                ap_NS_fsm = ap_ST_st20_fsm_19;
            end else if (((ap_const_lv1_0 == or_cond_reg_827) & (ap_const_lv1_0 == tmp_54_reg_844) & (ap_const_lv1_0 == tmp_36_reg_848) & ~(ap_const_lv1_0 == tmp_62_reg_853) & (ap_const_lv1_0 == exitcond_fu_555_p2) & (ap_const_lv1_0 == or_cond4_fu_585_p2) & ~((ap_const_lv1_0 == or_cond_reg_827) & (ap_const_lv1_0 == tmp_54_reg_844) & (ap_const_lv1_0 == tmp_36_reg_848) & ~(ap_const_lv1_0 == tmp_62_reg_853) & (ap_const_lv1_0 == exitcond_fu_555_p2) & ~(ap_const_lv1_0 == or_cond4_fu_585_p2) & (ap_const_logic_0 == ap_sig_ioackin_m_axi_inSound_AWREADY)))) begin
                ap_NS_fsm = ap_ST_st33_fsm_32;
            end else if (((ap_const_lv1_0 == or_cond_reg_827) & (ap_const_lv1_0 == tmp_54_reg_844) & (ap_const_lv1_0 == tmp_36_reg_848) & ~(ap_const_lv1_0 == tmp_62_reg_853) & (ap_const_lv1_0 == exitcond_fu_555_p2) & ~(ap_const_lv1_0 == or_cond4_fu_585_p2) & ~((ap_const_lv1_0 == or_cond_reg_827) & (ap_const_lv1_0 == tmp_54_reg_844) & (ap_const_lv1_0 == tmp_36_reg_848) & ~(ap_const_lv1_0 == tmp_62_reg_853) & (ap_const_lv1_0 == exitcond_fu_555_p2) & ~(ap_const_lv1_0 == or_cond4_fu_585_p2) & (ap_const_logic_0 == ap_sig_ioackin_m_axi_inSound_AWREADY)))) begin
                ap_NS_fsm = ap_ST_st29_fsm_28;
            end else begin
                ap_NS_fsm = ap_ST_st28_fsm_27;
            end
        end
        ap_ST_st29_fsm_28 : 
        begin
            if (~(ap_const_logic_0 == ap_sig_ioackin_m_axi_inSound_WREADY)) begin
                ap_NS_fsm = ap_ST_st30_fsm_29;
            end else begin
                ap_NS_fsm = ap_ST_st29_fsm_28;
            end
        end
        ap_ST_st30_fsm_29 : 
        begin
            ap_NS_fsm = ap_ST_st31_fsm_30;
        end
        ap_ST_st31_fsm_30 : 
        begin
            ap_NS_fsm = ap_ST_st32_fsm_31;
        end
        ap_ST_st32_fsm_31 : 
        begin
            ap_NS_fsm = ap_ST_st33_fsm_32;
        end
        ap_ST_st33_fsm_32 : 
        begin
            if (~ap_sig_bdd_394) begin
                ap_NS_fsm = ap_ST_st28_fsm_27;
            end else begin
                ap_NS_fsm = ap_ST_st33_fsm_32;
            end
        end
        ap_ST_st34_fsm_33 : 
        begin
            if ((~((ap_const_logic_0 == ap_sig_ioackin_m_axi_inSound_ARREADY) & (ap_const_lv1_0 == exitcond2_fu_622_p2) & (ap_const_lv1_0 == or_cond6_fu_658_p2)) & ~(ap_const_lv1_0 == exitcond2_fu_622_p2))) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else if (((ap_const_lv1_0 == exitcond2_fu_622_p2) & ~((ap_const_logic_0 == ap_sig_ioackin_m_axi_inSound_ARREADY) & (ap_const_lv1_0 == exitcond2_fu_622_p2) & (ap_const_lv1_0 == or_cond6_fu_658_p2)) & ~(ap_const_lv1_0 == or_cond6_fu_658_p2))) begin
                ap_NS_fsm = ap_ST_st41_fsm_40;
            end else if (((ap_const_lv1_0 == exitcond2_fu_622_p2) & (ap_const_lv1_0 == or_cond6_fu_658_p2) & ~((ap_const_logic_0 == ap_sig_ioackin_m_axi_inSound_ARREADY) & (ap_const_lv1_0 == exitcond2_fu_622_p2) & (ap_const_lv1_0 == or_cond6_fu_658_p2)))) begin
                ap_NS_fsm = ap_ST_st35_fsm_34;
            end else begin
                ap_NS_fsm = ap_ST_st34_fsm_33;
            end
        end
        ap_ST_st35_fsm_34 : 
        begin
            ap_NS_fsm = ap_ST_st36_fsm_35;
        end
        ap_ST_st36_fsm_35 : 
        begin
            ap_NS_fsm = ap_ST_st37_fsm_36;
        end
        ap_ST_st37_fsm_36 : 
        begin
            ap_NS_fsm = ap_ST_st38_fsm_37;
        end
        ap_ST_st38_fsm_37 : 
        begin
            ap_NS_fsm = ap_ST_st39_fsm_38;
        end
        ap_ST_st39_fsm_38 : 
        begin
            ap_NS_fsm = ap_ST_st40_fsm_39;
        end
        ap_ST_st40_fsm_39 : 
        begin
            if (~(m_axi_inSound_RVALID == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st41_fsm_40;
            end else begin
                ap_NS_fsm = ap_ST_st40_fsm_39;
            end
        end
        ap_ST_st41_fsm_40 : 
        begin
            ap_NS_fsm = ap_ST_st34_fsm_33;
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end


/// ap_sig_bdd_129 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_129 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_6]);
end

/// ap_sig_bdd_137 assign process. ///
always @ (m_axi_inSound_RVALID or tmp_fu_264_p2)
begin
    ap_sig_bdd_137 = ((m_axi_inSound_RVALID == ap_const_logic_0) & ~(tmp_fu_264_p2 == ap_const_lv1_0));
end

/// ap_sig_bdd_146 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_146 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_10]);
end

/// ap_sig_bdd_156 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_156 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_19]);
end

/// ap_sig_bdd_165 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_165 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_27]);
end

/// ap_sig_bdd_179 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_179 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_7]);
end

/// ap_sig_bdd_188 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_188 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_9]);
end

/// ap_sig_bdd_203 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_203 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_A]);
end

/// ap_sig_bdd_216 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_216 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_11]);
end

/// ap_sig_bdd_225 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_225 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_13]);
end

/// ap_sig_bdd_247 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_247 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1A]);
end

/// ap_sig_bdd_264 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_264 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1B]);
end

/// ap_sig_bdd_299 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_299 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_21]);
end

/// ap_sig_bdd_322 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_322 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_5]);
end

/// ap_sig_bdd_329 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_329 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_8]);
end

/// ap_sig_bdd_352 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_352 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_12]);
end

/// ap_sig_bdd_388 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_388 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_20]);
end

/// ap_sig_bdd_394 assign process. ///
always @ (m_axi_inSound_BVALID or or_cond4_reg_865)
begin
    ap_sig_bdd_394 = ((m_axi_inSound_BVALID == ap_const_logic_0) & ~(ap_const_lv1_0 == or_cond4_reg_865));
end

/// ap_sig_bdd_411 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_411 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_28]);
end

/// ap_sig_bdd_432 assign process. ///
always @ (ap_sig_cseq_ST_st20_fsm_19 or exitcond1_fu_398_p2 or or_cond_fu_422_p2)
begin
    ap_sig_bdd_432 = ((ap_const_logic_1 == ap_sig_cseq_ST_st20_fsm_19) & (ap_const_lv1_0 == exitcond1_fu_398_p2) & (ap_const_lv1_0 == or_cond_fu_422_p2));
end

/// ap_sig_bdd_434 assign process. ///
always @ (or_cond_reg_827 or tmp_54_reg_844 or tmp_36_reg_848 or tmp_62_reg_853 or ap_sig_cseq_ST_st28_fsm_27 or exitcond_fu_555_p2 or or_cond4_fu_585_p2)
begin
    ap_sig_bdd_434 = ((ap_const_logic_1 == ap_sig_cseq_ST_st28_fsm_27) & (ap_const_lv1_0 == or_cond_reg_827) & (ap_const_lv1_0 == tmp_54_reg_844) & (ap_const_lv1_0 == tmp_36_reg_848) & ~(ap_const_lv1_0 == tmp_62_reg_853) & (ap_const_lv1_0 == exitcond_fu_555_p2) & ~(ap_const_lv1_0 == or_cond4_fu_585_p2));
end

/// ap_sig_bdd_436 assign process. ///
always @ (ap_sig_cseq_ST_st34_fsm_33 or exitcond2_fu_622_p2 or or_cond6_fu_658_p2)
begin
    ap_sig_bdd_436 = ((ap_const_logic_1 == ap_sig_cseq_ST_st34_fsm_33) & (ap_const_lv1_0 == exitcond2_fu_622_p2) & (ap_const_lv1_0 == or_cond6_fu_658_p2));
end

/// ap_sig_bdd_441 assign process. ///
always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0)
begin
    ap_sig_bdd_441 = ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0));
end

/// ap_sig_bdd_478 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_478 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1C]);
end

/// ap_sig_bdd_59 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_59 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end
assign count_1_fu_521_p2 = (count_fu_86 + ap_const_lv32_1);
assign exitcond1_fu_398_p2 = (markBegin_2_reg_186 == ap_const_lv14_3E80? 1'b1: 1'b0);
assign exitcond2_fu_622_p2 = (i_3_reg_209 == ap_const_lv14_3E80? 1'b1: 1'b0);
assign exitcond_fu_555_p2 = (j9_reg_198 == ap_const_lv14_3E80? 1'b1: 1'b0);
assign grp_fu_247_p2 = (j_1_fu_94 + ap_const_lv32_1);
assign i_1_in_cast_fu_318_p1 = i_1_in_reg_163;
assign i_3_cast_fu_618_p1 = i_3_reg_209;
assign i_4_fu_628_p2 = (i_3_reg_209 + ap_const_lv14_1);
assign i_5_fu_404_p2 = (markBegin_2_reg_186 + ap_const_lv14_1);
assign i_fu_270_p2 = (first_reg_138 + ap_const_lv14_1);
assign inSound_load_1_to_int_fu_352_p1 = reg_258;
assign inSound_load_to_int_fu_276_p1 = reg_258;
assign j9_cast3_fu_551_p1 = j9_reg_198;
assign j_8_fu_561_p2 = (j9_reg_198 + ap_const_lv14_1);
assign last_2_cast5_fu_328_p1 = last_2_fu_322_p2;
assign last_2_fu_322_p2 = ($signed(ap_const_lv15_7FFF) + $signed(i_1_in_cast_fu_318_p1));
assign m_axi_inSound_ARBURST = ap_const_lv2_0;
assign m_axi_inSound_ARCACHE = ap_const_lv4_0;
assign m_axi_inSound_ARID = ap_const_lv1_0;
assign m_axi_inSound_ARLOCK = ap_const_lv2_0;
assign m_axi_inSound_ARPROT = ap_const_lv3_0;
assign m_axi_inSound_ARQOS = ap_const_lv4_0;
assign m_axi_inSound_ARREGION = ap_const_lv4_0;
assign m_axi_inSound_ARSIZE = ap_const_lv3_0;
assign m_axi_inSound_ARUSER = ap_const_lv1_0;
assign m_axi_inSound_AWADDR = tmp_65_fu_591_p1;
assign m_axi_inSound_AWBURST = ap_const_lv2_0;
assign m_axi_inSound_AWCACHE = ap_const_lv4_0;
assign m_axi_inSound_AWID = ap_const_lv1_0;
assign m_axi_inSound_AWLEN = ap_const_lv32_1;
assign m_axi_inSound_AWLOCK = ap_const_lv2_0;
assign m_axi_inSound_AWPROT = ap_const_lv3_0;
assign m_axi_inSound_AWQOS = ap_const_lv4_0;
assign m_axi_inSound_AWREGION = ap_const_lv4_0;
assign m_axi_inSound_AWSIZE = ap_const_lv3_0;
assign m_axi_inSound_AWUSER = ap_const_lv1_0;
assign m_axi_inSound_WDATA = ap_const_lv64_0;
assign m_axi_inSound_WID = ap_const_lv1_0;
assign m_axi_inSound_WLAST = ap_const_logic_0;
assign m_axi_inSound_WSTRB = ap_const_lv8_FF;
assign m_axi_inSound_WUSER = ap_const_lv1_0;
assign markBegin_1_cast_fu_609_p1 = markBegin_1_fu_602_p3;
assign markBegin_1_fu_602_p3 = ((tmp_36_reg_848[0:0]===1'b1)? markBegin_2_reg_186: ap_const_lv14_0);
assign markBegin_2_cast_fu_394_p1 = markBegin_2_reg_186;
assign notlhs1_fu_294_p2 = (tmp_15_fu_280_p4 != ap_const_lv11_7FF? 1'b1: 1'b0);
assign notlhs2_fu_370_p2 = (tmp_20_fu_356_p4 != ap_const_lv11_7FF? 1'b1: 1'b0);
assign notlhs3_fu_727_p2 = (tmp_27_fu_717_p4 != ap_const_lv11_7FF? 1'b1: 1'b0);
assign notlhs4_fu_485_p2 = (tmp_33_fu_475_p4 != ap_const_lv11_7FF? 1'b1: 1'b0);
assign notrhs1_fu_300_p2 = (tmp_21_fu_290_p1 == ap_const_lv52_0? 1'b1: 1'b0);
assign notrhs2_fu_376_p2 = (tmp_26_fu_366_p1 == ap_const_lv52_0? 1'b1: 1'b0);
assign notrhs3_fu_733_p2 = (tmp_38_fu_700_p1 == ap_const_lv52_0? 1'b1: 1'b0);
assign notrhs4_fu_491_p2 = (tmp_32_fu_458_p1 == ap_const_lv52_0? 1'b1: 1'b0);
assign or_cond4_fu_585_p2 = (rev_fu_573_p2 & tmp_64_fu_579_p2);
assign or_cond6_fu_658_p2 = (tmp1_fu_652_p2 | tmp_51_fu_634_p2);
assign or_cond7_fu_681_p2 = (tmp_55_fu_675_p2 | tmp_51_fu_634_p2);
assign or_cond_fu_422_p2 = (tmp_49_fu_410_p2 | tmp_50_fu_416_p2);
assign p_Result_1_fu_704_p3 = {{ap_const_lv1_0}, {tmp_37_fu_696_p1}};
assign p_Result_s_fu_462_p3 = {{ap_const_lv1_0}, {tmp_31_fu_454_p1}};
assign p_Val2_1_fu_692_p1 = reg_258;
assign p_Val2_s_fu_450_p1 = reg_258;
assign p_deleteFlag_fu_533_p3 = ((tmp_61_fu_527_p2[0:0]===1'b1)? ap_const_lv32_1: deleteFlag_fu_82);
assign ret_i_i_i_i_i2_fu_712_p1 = p_Result_1_fu_704_p3;
assign ret_i_i_i_i_i_fu_470_p1 = p_Result_s_fu_462_p3;
assign rev_fu_573_p2 = (slt_fu_567_p2 ^ ap_const_lv1_1);
assign slt_fu_567_p2 = ($signed(j9_cast3_fu_551_p1) < $signed(markBegin_fu_90)? 1'b1: 1'b0);
assign tmp1_fu_652_p2 = (tmp_52_fu_640_p2 | tmp_53_fu_646_p2);
assign tmp_15_fu_280_p4 = {{inSound_load_to_int_fu_276_p1[ap_const_lv32_3E : ap_const_lv32_34]}};
assign tmp_17_fu_306_p2 = (notrhs1_fu_300_p2 | notlhs1_fu_294_p2);
assign tmp_19_fu_312_p2 = (tmp_17_fu_306_p2 & grp_fu_220_p2);
assign tmp_20_fu_356_p4 = {{inSound_load_1_to_int_fu_352_p1[ap_const_lv32_3E : ap_const_lv32_34]}};
assign tmp_21_fu_290_p1 = inSound_load_to_int_fu_276_p1[51:0];
assign tmp_22_fu_382_p2 = (notrhs2_fu_376_p2 | notlhs2_fu_370_p2);
assign tmp_24_fu_388_p2 = (tmp_22_fu_382_p2 & grp_fu_220_p2);
assign tmp_25_fu_332_p1 = last_2_fu_322_p2[13:0];
assign tmp_26_fu_366_p1 = inSound_load_1_to_int_fu_352_p1[51:0];
assign tmp_27_fu_717_p4 = {{p_Val2_1_fu_692_p1[ap_const_lv32_3E : ap_const_lv32_34]}};
assign tmp_28_fu_739_p2 = (notrhs3_fu_733_p2 | notlhs3_fu_727_p2);
assign tmp_30_fu_745_p2 = (tmp_28_fu_739_p2 & grp_fu_220_p2);
assign tmp_31_fu_454_p1 = p_Val2_s_fu_450_p1[62:0];
assign tmp_32_fu_458_p1 = p_Val2_s_fu_450_p1[51:0];
assign tmp_33_fu_475_p4 = {{p_Val2_s_fu_450_p1[ap_const_lv32_3E : ap_const_lv32_34]}};
assign tmp_34_fu_497_p2 = (notrhs4_fu_491_p2 | notlhs4_fu_485_p2);
assign tmp_36_fu_503_p2 = (tmp_34_fu_497_p2 & grp_fu_220_p2);
assign tmp_37_fu_696_p1 = p_Val2_1_fu_692_p1[62:0];
assign tmp_38_fu_700_p1 = p_Val2_1_fu_692_p1[51:0];
assign tmp_47_fu_336_p2 = (i_1_in_reg_163 == ap_const_lv14_0? 1'b1: 1'b0);
assign tmp_48_fu_342_p1 = $unsigned(last_2_cast5_reg_774);
assign tmp_49_fu_410_p2 = (markBegin_2_reg_186 < first1_reg_150? 1'b1: 1'b0);
assign tmp_50_fu_416_p2 = ($signed(markBegin_2_cast_fu_394_p1) > $signed(last_reg_174)? 1'b1: 1'b0);
assign tmp_51_fu_634_p2 = (i_3_reg_209 < first1_reg_150? 1'b1: 1'b0);
assign tmp_52_fu_640_p2 = ($signed(i_3_cast_fu_618_p1) > $signed(last_reg_174)? 1'b1: 1'b0);
assign tmp_53_fu_646_p2 = (j_1_fu_94 == ap_const_lv32_1F40? 1'b1: 1'b0);
assign tmp_54_fu_444_p2 = (markBegin_fu_90 == ap_const_lv32_0? 1'b1: 1'b0);
assign tmp_55_fu_675_p2 = ($signed(j_1_fu_94) > $signed(32'b1111100111111)? 1'b1: 1'b0);
assign tmp_56_fu_664_p1 = i_3_reg_209;
assign tmp_57_fu_428_p1 = markBegin_2_reg_186;
assign tmp_59_fu_687_p1 = $signed(j_1_fu_94);
assign tmp_60_fu_751_p1 = $signed(j_1_fu_94);
assign tmp_61_fu_527_p2 = (count_1_fu_521_p2 == ap_const_lv32_C8? 1'b1: 1'b0);
assign tmp_62_fu_512_p2 = (deleteFlag_fu_82 == ap_const_lv32_1? 1'b1: 1'b0);
assign tmp_64_fu_579_p2 = (j9_reg_198 < markBegin_2_reg_186? 1'b1: 1'b0);
assign tmp_65_fu_591_p1 = j9_reg_198;
assign tmp_fu_264_p2 = (first_reg_138 < ap_const_lv14_3E80? 1'b1: 1'b0);
always @ (posedge ap_clk)
begin
    markBegin_fu_90[31:14] <= 18'b000000000000000000;
end



endmodule //voicerec_preprocessSound

