webtalk_init -webtalk_dir C:\\Users\\rz252\\Desktop\\test\\ece5775-final\\audio_lab\\audio3\\audio.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Dec 11 20:27:11 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210679823_1777488264_210608356_669" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "9mm581h0hesuve1a95vv7dkv98" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.4_9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "9" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM)2 Quad CPU    Q6600  @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1449875633422" -context "sdk\\\\hardware/1449875633422"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1449875633422"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1449875633422"
webtalk_add_data -client sdk -key VivadoVersion -value "2014.4" -context "sdk\\\\hardware/1449875633422"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1449875633422"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1449875633422"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1449875633422"
webtalk_transmit -clientid 564629691 -regid "210679823_1777488264_210608356_669" -xml C:\\Users\\rz252\\Desktop\\test\\ece5775-final\\audio_lab\\audio3\\audio.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\rz252\\Desktop\\test\\ece5775-final\\audio_lab\\audio3\\audio.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\rz252\\Desktop\\test\\ece5775-final\\audio_lab\\audio3\\audio.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
